/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ArrayOfBooleansResponse,
  BadRequestResponse,
  CheckUsersSavedAudiobooksParams,
  ForbiddenResponse,
  GetAnAudiobookParams,
  GetAudiobookChaptersParams,
  GetMultipleAudiobooksParams,
  GetUsersSavedAudiobooksParams,
  ManyAudiobooksResponse,
  NotFoundResponse,
  OneAudiobookResponse,
  PagingSavedAudiobookObjectResponse,
  PagingSimplifiedChapterObjectResponse,
  RemoveAudiobooksUserParams,
  SaveAudiobooksUserParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single audiobook.<br />
**Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Get an Audiobook

 */
export type getAnAudiobookResponse200 = {
  data: OneAudiobookResponse
  status: 200
}

export type getAnAudiobookResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getAnAudiobookResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnAudiobookResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnAudiobookResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getAnAudiobookResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnAudiobookResponseSuccess = (getAnAudiobookResponse200) & {
  headers: Headers;
};
export type getAnAudiobookResponseError = (getAnAudiobookResponse400 | getAnAudiobookResponse401 | getAnAudiobookResponse403 | getAnAudiobookResponse404 | getAnAudiobookResponse429) & {
  headers: Headers;
};

export type getAnAudiobookResponse = (getAnAudiobookResponseSuccess | getAnAudiobookResponseError)

export const getGetAnAudiobookUrl = (id: string,
    params?: GetAnAudiobookParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/audiobooks/${id}?${stringifiedParams}` : `https://api.spotify.com/v1/audiobooks/${id}`
}

export const getAnAudiobook = async (id: string,
    params?: GetAnAudiobookParams, options?: RequestInit): Promise<getAnAudiobookResponse> => {
  
  const res = await fetch(getGetAnAudiobookUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnAudiobookResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnAudiobookResponse
}




export const getGetAnAudiobookKey = (id: string,
    params?: GetAnAudiobookParams,) => [`https://api.spotify.com/v1/audiobooks/${id}`, ...(params ? [params]: [])] as const;

export type GetAnAudiobookQueryResult = NonNullable<Awaited<ReturnType<typeof getAnAudiobook>>>

/**
 * @summary Get an Audiobook

 */
export const useGetAnAudiobook = <TError = Promise<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnAudiobookParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnAudiobook>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnAudiobookKey(id,params) : null);
  const swrFn = () => getAnAudiobook(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for several audiobooks identified by their Spotify IDs.<br />
**Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Get Several Audiobooks

 */
export type getMultipleAudiobooksResponse200 = {
  data: ManyAudiobooksResponse
  status: 200
}

export type getMultipleAudiobooksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMultipleAudiobooksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMultipleAudiobooksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getMultipleAudiobooksResponseSuccess = (getMultipleAudiobooksResponse200) & {
  headers: Headers;
};
export type getMultipleAudiobooksResponseError = (getMultipleAudiobooksResponse401 | getMultipleAudiobooksResponse403 | getMultipleAudiobooksResponse429) & {
  headers: Headers;
};

export type getMultipleAudiobooksResponse = (getMultipleAudiobooksResponseSuccess | getMultipleAudiobooksResponseError)

export const getGetMultipleAudiobooksUrl = (params: GetMultipleAudiobooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/audiobooks?${stringifiedParams}` : `https://api.spotify.com/v1/audiobooks`
}

export const getMultipleAudiobooks = async (params: GetMultipleAudiobooksParams, options?: RequestInit): Promise<getMultipleAudiobooksResponse> => {
  
  const res = await fetch(getGetMultipleAudiobooksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMultipleAudiobooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMultipleAudiobooksResponse
}




export const getGetMultipleAudiobooksKey = (params: GetMultipleAudiobooksParams,) => [`https://api.spotify.com/v1/audiobooks`, ...(params ? [params]: [])] as const;

export type GetMultipleAudiobooksQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleAudiobooks>>>

/**
 * @summary Get Several Audiobooks

 */
export const useGetMultipleAudiobooks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetMultipleAudiobooksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMultipleAudiobooks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMultipleAudiobooksKey(params) : null);
  const swrFn = () => getMultipleAudiobooks(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about an audiobook's chapters.<br />
**Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Get Audiobook Chapters

 */
export type getAudiobookChaptersResponse200 = {
  data: PagingSimplifiedChapterObjectResponse
  status: 200
}

export type getAudiobookChaptersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAudiobookChaptersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAudiobookChaptersResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAudiobookChaptersResponseSuccess = (getAudiobookChaptersResponse200) & {
  headers: Headers;
};
export type getAudiobookChaptersResponseError = (getAudiobookChaptersResponse401 | getAudiobookChaptersResponse403 | getAudiobookChaptersResponse429) & {
  headers: Headers;
};

export type getAudiobookChaptersResponse = (getAudiobookChaptersResponseSuccess | getAudiobookChaptersResponseError)

export const getGetAudiobookChaptersUrl = (id: string,
    params?: GetAudiobookChaptersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/audiobooks/${id}/chapters?${stringifiedParams}` : `https://api.spotify.com/v1/audiobooks/${id}/chapters`
}

export const getAudiobookChapters = async (id: string,
    params?: GetAudiobookChaptersParams, options?: RequestInit): Promise<getAudiobookChaptersResponse> => {
  
  const res = await fetch(getGetAudiobookChaptersUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAudiobookChaptersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAudiobookChaptersResponse
}




export const getGetAudiobookChaptersKey = (id: string,
    params?: GetAudiobookChaptersParams,) => [`https://api.spotify.com/v1/audiobooks/${id}/chapters`, ...(params ? [params]: [])] as const;

export type GetAudiobookChaptersQueryResult = NonNullable<Awaited<ReturnType<typeof getAudiobookChapters>>>

/**
 * @summary Get Audiobook Chapters

 */
export const useGetAudiobookChapters = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAudiobookChaptersParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAudiobookChapters>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAudiobookChaptersKey(id,params) : null);
  const swrFn = () => getAudiobookChapters(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.

 * @summary Get User's Saved Audiobooks

 */
export type getUsersSavedAudiobooksResponse200 = {
  data: PagingSavedAudiobookObjectResponse
  status: 200
}

export type getUsersSavedAudiobooksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersSavedAudiobooksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersSavedAudiobooksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersSavedAudiobooksResponseSuccess = (getUsersSavedAudiobooksResponse200) & {
  headers: Headers;
};
export type getUsersSavedAudiobooksResponseError = (getUsersSavedAudiobooksResponse401 | getUsersSavedAudiobooksResponse403 | getUsersSavedAudiobooksResponse429) & {
  headers: Headers;
};

export type getUsersSavedAudiobooksResponse = (getUsersSavedAudiobooksResponseSuccess | getUsersSavedAudiobooksResponseError)

export const getGetUsersSavedAudiobooksUrl = (params?: GetUsersSavedAudiobooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/audiobooks?${stringifiedParams}` : `https://api.spotify.com/v1/me/audiobooks`
}

export const getUsersSavedAudiobooks = async (params?: GetUsersSavedAudiobooksParams, options?: RequestInit): Promise<getUsersSavedAudiobooksResponse> => {
  
  const res = await fetch(getGetUsersSavedAudiobooksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersSavedAudiobooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersSavedAudiobooksResponse
}




export const getGetUsersSavedAudiobooksKey = (params?: GetUsersSavedAudiobooksParams,) => [`https://api.spotify.com/v1/me/audiobooks`, ...(params ? [params]: [])] as const;

export type GetUsersSavedAudiobooksQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersSavedAudiobooks>>>

/**
 * @summary Get User's Saved Audiobooks

 */
export const useGetUsersSavedAudiobooks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersSavedAudiobooksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersSavedAudiobooks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersSavedAudiobooksKey(params) : null);
  const swrFn = () => getUsersSavedAudiobooks(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Save one or more audiobooks to the current Spotify user's library.

 * @summary Save Audiobooks for Current User

 */
export type saveAudiobooksUserResponse200 = {
  data: void
  status: 200
}

export type saveAudiobooksUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type saveAudiobooksUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type saveAudiobooksUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type saveAudiobooksUserResponseSuccess = (saveAudiobooksUserResponse200) & {
  headers: Headers;
};
export type saveAudiobooksUserResponseError = (saveAudiobooksUserResponse401 | saveAudiobooksUserResponse403 | saveAudiobooksUserResponse429) & {
  headers: Headers;
};

export type saveAudiobooksUserResponse = (saveAudiobooksUserResponseSuccess | saveAudiobooksUserResponseError)

export const getSaveAudiobooksUserUrl = (params: SaveAudiobooksUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/audiobooks?${stringifiedParams}` : `https://api.spotify.com/v1/me/audiobooks`
}

export const saveAudiobooksUser = async (params: SaveAudiobooksUserParams, options?: RequestInit): Promise<saveAudiobooksUserResponse> => {
  
  const res = await fetch(getSaveAudiobooksUserUrl(params),
  {      
    ...options,
    method: 'PUT'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: saveAudiobooksUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveAudiobooksUserResponse
}




export const getSaveAudiobooksUserMutationFetcher = (params: SaveAudiobooksUserParams, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return saveAudiobooksUser(params, options);
  }
}
export const getSaveAudiobooksUserMutationKey = (params: SaveAudiobooksUserParams,) => [`https://api.spotify.com/v1/me/audiobooks`, ...(params ? [params]: [])] as const;

export type SaveAudiobooksUserMutationResult = NonNullable<Awaited<ReturnType<typeof saveAudiobooksUser>>>

/**
 * @summary Save Audiobooks for Current User

 */
export const useSaveAudiobooksUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: SaveAudiobooksUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof saveAudiobooksUser>>, TError, Key, Arguments, Awaited<ReturnType<typeof saveAudiobooksUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSaveAudiobooksUserMutationKey(params);
  const swrFn = getSaveAudiobooksUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove one or more audiobooks from the Spotify user's library.

 * @summary Remove User's Saved Audiobooks

 */
export type removeAudiobooksUserResponse200 = {
  data: void
  status: 200
}

export type removeAudiobooksUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeAudiobooksUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeAudiobooksUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type removeAudiobooksUserResponseSuccess = (removeAudiobooksUserResponse200) & {
  headers: Headers;
};
export type removeAudiobooksUserResponseError = (removeAudiobooksUserResponse401 | removeAudiobooksUserResponse403 | removeAudiobooksUserResponse429) & {
  headers: Headers;
};

export type removeAudiobooksUserResponse = (removeAudiobooksUserResponseSuccess | removeAudiobooksUserResponseError)

export const getRemoveAudiobooksUserUrl = (params: RemoveAudiobooksUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/audiobooks?${stringifiedParams}` : `https://api.spotify.com/v1/me/audiobooks`
}

export const removeAudiobooksUser = async (params: RemoveAudiobooksUserParams, options?: RequestInit): Promise<removeAudiobooksUserResponse> => {
  
  const res = await fetch(getRemoveAudiobooksUserUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeAudiobooksUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeAudiobooksUserResponse
}




export const getRemoveAudiobooksUserMutationFetcher = (params: RemoveAudiobooksUserParams, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return removeAudiobooksUser(params, options);
  }
}
export const getRemoveAudiobooksUserMutationKey = (params: RemoveAudiobooksUserParams,) => [`https://api.spotify.com/v1/me/audiobooks`, ...(params ? [params]: [])] as const;

export type RemoveAudiobooksUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeAudiobooksUser>>>

/**
 * @summary Remove User's Saved Audiobooks

 */
export const useRemoveAudiobooksUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: RemoveAudiobooksUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeAudiobooksUser>>, TError, Key, Arguments, Awaited<ReturnType<typeof removeAudiobooksUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveAudiobooksUserMutationKey(params);
  const swrFn = getRemoveAudiobooksUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check if one or more audiobooks are already saved in the current Spotify user's library.

 * @summary Check User's Saved Audiobooks

 */
export type checkUsersSavedAudiobooksResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkUsersSavedAudiobooksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkUsersSavedAudiobooksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkUsersSavedAudiobooksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkUsersSavedAudiobooksResponseSuccess = (checkUsersSavedAudiobooksResponse200) & {
  headers: Headers;
};
export type checkUsersSavedAudiobooksResponseError = (checkUsersSavedAudiobooksResponse401 | checkUsersSavedAudiobooksResponse403 | checkUsersSavedAudiobooksResponse429) & {
  headers: Headers;
};

export type checkUsersSavedAudiobooksResponse = (checkUsersSavedAudiobooksResponseSuccess | checkUsersSavedAudiobooksResponseError)

export const getCheckUsersSavedAudiobooksUrl = (params: CheckUsersSavedAudiobooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/audiobooks/contains?${stringifiedParams}` : `https://api.spotify.com/v1/me/audiobooks/contains`
}

export const checkUsersSavedAudiobooks = async (params: CheckUsersSavedAudiobooksParams, options?: RequestInit): Promise<checkUsersSavedAudiobooksResponse> => {
  
  const res = await fetch(getCheckUsersSavedAudiobooksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkUsersSavedAudiobooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkUsersSavedAudiobooksResponse
}




export const getCheckUsersSavedAudiobooksKey = (params: CheckUsersSavedAudiobooksParams,) => [`https://api.spotify.com/v1/me/audiobooks/contains`, ...(params ? [params]: [])] as const;

export type CheckUsersSavedAudiobooksQueryResult = NonNullable<Awaited<ReturnType<typeof checkUsersSavedAudiobooks>>>

/**
 * @summary Check User's Saved Audiobooks

 */
export const useCheckUsersSavedAudiobooks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckUsersSavedAudiobooksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkUsersSavedAudiobooks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckUsersSavedAudiobooksKey(params) : null);
  const swrFn = () => checkUsersSavedAudiobooks(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
