/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  ManyGenresResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-api/reference/get-recommendations).

 * @summary Get Available Genre Seeds

 */
export type getRecommendationGenresResponse200 = {
  data: ManyGenresResponse
  status: 200
}

export type getRecommendationGenresResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getRecommendationGenresResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getRecommendationGenresResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getRecommendationGenresResponseSuccess = (getRecommendationGenresResponse200) & {
  headers: Headers;
};
export type getRecommendationGenresResponseError = (getRecommendationGenresResponse401 | getRecommendationGenresResponse403 | getRecommendationGenresResponse429) & {
  headers: Headers;
};

export type getRecommendationGenresResponse = (getRecommendationGenresResponseSuccess | getRecommendationGenresResponseError)

export const getGetRecommendationGenresUrl = () => {


  

  return `https://api.spotify.com/v1/recommendations/available-genre-seeds`
}

export const getRecommendationGenres = async ( options?: RequestInit): Promise<getRecommendationGenresResponse> => {
  
  const res = await fetch(getGetRecommendationGenresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRecommendationGenresResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRecommendationGenresResponse
}




export const getGetRecommendationGenresKey = () => [`https://api.spotify.com/v1/recommendations/available-genre-seeds`] as const;

export type GetRecommendationGenresQueryResult = NonNullable<Awaited<ReturnType<typeof getRecommendationGenres>>>

/**
 * @summary Get Available Genre Seeds

 */
export const useGetRecommendationGenres = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getRecommendationGenres>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetRecommendationGenresKey() : null);
  const swrFn = () => getRecommendationGenres(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
