/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  GetAnArtistsAlbumsParams,
  GetAnArtistsTopTracksParams,
  GetMultipleArtistsParams,
  ManyArtistsResponse,
  ManyTracksResponse,
  OneArtistResponse,
  PagingArtistDiscographyAlbumObjectResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single artist identified by their unique Spotify ID.

 * @summary Get Artist

 */
export type getAnArtistResponse200 = {
  data: OneArtistResponse
  status: 200
}

export type getAnArtistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnArtistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnArtistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnArtistResponseSuccess = (getAnArtistResponse200) & {
  headers: Headers;
};
export type getAnArtistResponseError = (getAnArtistResponse401 | getAnArtistResponse403 | getAnArtistResponse429) & {
  headers: Headers;
};

export type getAnArtistResponse = (getAnArtistResponseSuccess | getAnArtistResponseError)

export const getGetAnArtistUrl = (id: string,) => {


  

  return `https://api.spotify.com/v1/artists/${id}`
}

export const getAnArtist = async (id: string, options?: RequestInit): Promise<getAnArtistResponse> => {
  
  const res = await fetch(getGetAnArtistUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnArtistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnArtistResponse
}




export const getGetAnArtistKey = (id: string,) => [`https://api.spotify.com/v1/artists/${id}`] as const;

export type GetAnArtistQueryResult = NonNullable<Awaited<ReturnType<typeof getAnArtist>>>

/**
 * @summary Get Artist

 */
export const useGetAnArtist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnArtist>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnArtistKey(id) : null);
  const swrFn = () => getAnArtist(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for several artists based on their Spotify IDs.

 * @summary Get Several Artists

 */
export type getMultipleArtistsResponse200 = {
  data: ManyArtistsResponse
  status: 200
}

export type getMultipleArtistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMultipleArtistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMultipleArtistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getMultipleArtistsResponseSuccess = (getMultipleArtistsResponse200) & {
  headers: Headers;
};
export type getMultipleArtistsResponseError = (getMultipleArtistsResponse401 | getMultipleArtistsResponse403 | getMultipleArtistsResponse429) & {
  headers: Headers;
};

export type getMultipleArtistsResponse = (getMultipleArtistsResponseSuccess | getMultipleArtistsResponseError)

export const getGetMultipleArtistsUrl = (params: GetMultipleArtistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/artists?${stringifiedParams}` : `https://api.spotify.com/v1/artists`
}

export const getMultipleArtists = async (params: GetMultipleArtistsParams, options?: RequestInit): Promise<getMultipleArtistsResponse> => {
  
  const res = await fetch(getGetMultipleArtistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMultipleArtistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMultipleArtistsResponse
}




export const getGetMultipleArtistsKey = (params: GetMultipleArtistsParams,) => [`https://api.spotify.com/v1/artists`, ...(params ? [params]: [])] as const;

export type GetMultipleArtistsQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleArtists>>>

/**
 * @summary Get Several Artists

 */
export const useGetMultipleArtists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetMultipleArtistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMultipleArtists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMultipleArtistsKey(params) : null);
  const swrFn = () => getMultipleArtists(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about an artist's albums.

 * @summary Get Artist's Albums

 */
export type getAnArtistsAlbumsResponse200 = {
  data: PagingArtistDiscographyAlbumObjectResponse
  status: 200
}

export type getAnArtistsAlbumsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnArtistsAlbumsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnArtistsAlbumsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnArtistsAlbumsResponseSuccess = (getAnArtistsAlbumsResponse200) & {
  headers: Headers;
};
export type getAnArtistsAlbumsResponseError = (getAnArtistsAlbumsResponse401 | getAnArtistsAlbumsResponse403 | getAnArtistsAlbumsResponse429) & {
  headers: Headers;
};

export type getAnArtistsAlbumsResponse = (getAnArtistsAlbumsResponseSuccess | getAnArtistsAlbumsResponseError)

export const getGetAnArtistsAlbumsUrl = (id: string,
    params?: GetAnArtistsAlbumsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/artists/${id}/albums?${stringifiedParams}` : `https://api.spotify.com/v1/artists/${id}/albums`
}

export const getAnArtistsAlbums = async (id: string,
    params?: GetAnArtistsAlbumsParams, options?: RequestInit): Promise<getAnArtistsAlbumsResponse> => {
  
  const res = await fetch(getGetAnArtistsAlbumsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnArtistsAlbumsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnArtistsAlbumsResponse
}




export const getGetAnArtistsAlbumsKey = (id: string,
    params?: GetAnArtistsAlbumsParams,) => [`https://api.spotify.com/v1/artists/${id}/albums`, ...(params ? [params]: [])] as const;

export type GetAnArtistsAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnArtistsAlbums>>>

/**
 * @summary Get Artist's Albums

 */
export const useGetAnArtistsAlbums = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnArtistsAlbumsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnArtistsAlbums>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnArtistsAlbumsKey(id,params) : null);
  const swrFn = () => getAnArtistsAlbums(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about an artist's top tracks by country.

 * @summary Get Artist's Top Tracks

 */
export type getAnArtistsTopTracksResponse200 = {
  data: ManyTracksResponse
  status: 200
}

export type getAnArtistsTopTracksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnArtistsTopTracksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnArtistsTopTracksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnArtistsTopTracksResponseSuccess = (getAnArtistsTopTracksResponse200) & {
  headers: Headers;
};
export type getAnArtistsTopTracksResponseError = (getAnArtistsTopTracksResponse401 | getAnArtistsTopTracksResponse403 | getAnArtistsTopTracksResponse429) & {
  headers: Headers;
};

export type getAnArtistsTopTracksResponse = (getAnArtistsTopTracksResponseSuccess | getAnArtistsTopTracksResponseError)

export const getGetAnArtistsTopTracksUrl = (id: string,
    params?: GetAnArtistsTopTracksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/artists/${id}/top-tracks?${stringifiedParams}` : `https://api.spotify.com/v1/artists/${id}/top-tracks`
}

export const getAnArtistsTopTracks = async (id: string,
    params?: GetAnArtistsTopTracksParams, options?: RequestInit): Promise<getAnArtistsTopTracksResponse> => {
  
  const res = await fetch(getGetAnArtistsTopTracksUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnArtistsTopTracksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnArtistsTopTracksResponse
}




export const getGetAnArtistsTopTracksKey = (id: string,
    params?: GetAnArtistsTopTracksParams,) => [`https://api.spotify.com/v1/artists/${id}/top-tracks`, ...(params ? [params]: [])] as const;

export type GetAnArtistsTopTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getAnArtistsTopTracks>>>

/**
 * @summary Get Artist's Top Tracks

 */
export const useGetAnArtistsTopTracks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnArtistsTopTracksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnArtistsTopTracks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnArtistsTopTracksKey(id,params) : null);
  const swrFn = () => getAnArtistsTopTracks(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's listening history.

 * @summary Get Artist's Related Artists

 */
export type getAnArtistsRelatedArtistsResponse200 = {
  data: ManyArtistsResponse
  status: 200
}

export type getAnArtistsRelatedArtistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnArtistsRelatedArtistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnArtistsRelatedArtistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnArtistsRelatedArtistsResponseSuccess = (getAnArtistsRelatedArtistsResponse200) & {
  headers: Headers;
};
export type getAnArtistsRelatedArtistsResponseError = (getAnArtistsRelatedArtistsResponse401 | getAnArtistsRelatedArtistsResponse403 | getAnArtistsRelatedArtistsResponse429) & {
  headers: Headers;
};

export type getAnArtistsRelatedArtistsResponse = (getAnArtistsRelatedArtistsResponseSuccess | getAnArtistsRelatedArtistsResponseError)

export const getGetAnArtistsRelatedArtistsUrl = (id: string,) => {


  

  return `https://api.spotify.com/v1/artists/${id}/related-artists`
}

export const getAnArtistsRelatedArtists = async (id: string, options?: RequestInit): Promise<getAnArtistsRelatedArtistsResponse> => {
  
  const res = await fetch(getGetAnArtistsRelatedArtistsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnArtistsRelatedArtistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnArtistsRelatedArtistsResponse
}




export const getGetAnArtistsRelatedArtistsKey = (id: string,) => [`https://api.spotify.com/v1/artists/${id}/related-artists`] as const;

export type GetAnArtistsRelatedArtistsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnArtistsRelatedArtists>>>

/**
 * @summary Get Artist's Related Artists

 */
export const useGetAnArtistsRelatedArtists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnArtistsRelatedArtists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnArtistsRelatedArtistsKey(id) : null);
  const swrFn = () => getAnArtistsRelatedArtists(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
