/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  GetACategoryParams,
  GetCategoriesParams,
  OneCategoryResponse,
  PagedCategoriesResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).

 * @summary Get Several Browse Categories

 */
export type getCategoriesResponse200 = {
  data: PagedCategoriesResponse
  status: 200
}

export type getCategoriesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCategoriesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getCategoriesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getCategoriesResponseSuccess = (getCategoriesResponse200) & {
  headers: Headers;
};
export type getCategoriesResponseError = (getCategoriesResponse401 | getCategoriesResponse403 | getCategoriesResponse429) & {
  headers: Headers;
};

export type getCategoriesResponse = (getCategoriesResponseSuccess | getCategoriesResponseError)

export const getGetCategoriesUrl = (params?: GetCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/browse/categories?${stringifiedParams}` : `https://api.spotify.com/v1/browse/categories`
}

export const getCategories = async (params?: GetCategoriesParams, options?: RequestInit): Promise<getCategoriesResponse> => {
  
  const res = await fetch(getGetCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCategoriesResponse
}




export const getGetCategoriesKey = (params?: GetCategoriesParams,) => [`https://api.spotify.com/v1/browse/categories`, ...(params ? [params]: [])] as const;

export type GetCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCategories>>>

/**
 * @summary Get Several Browse Categories

 */
export const useGetCategories = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetCategoriesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCategories>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCategoriesKey(params) : null);
  const swrFn = () => getCategories(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).

 * @summary Get Single Browse Category

 */
export type getACategoryResponse200 = {
  data: OneCategoryResponse
  status: 200
}

export type getACategoryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getACategoryResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getACategoryResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getACategoryResponseSuccess = (getACategoryResponse200) & {
  headers: Headers;
};
export type getACategoryResponseError = (getACategoryResponse401 | getACategoryResponse403 | getACategoryResponse429) & {
  headers: Headers;
};

export type getACategoryResponse = (getACategoryResponseSuccess | getACategoryResponseError)

export const getGetACategoryUrl = (categoryId: string,
    params?: GetACategoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/browse/categories/${categoryId}?${stringifiedParams}` : `https://api.spotify.com/v1/browse/categories/${categoryId}`
}

export const getACategory = async (categoryId: string,
    params?: GetACategoryParams, options?: RequestInit): Promise<getACategoryResponse> => {
  
  const res = await fetch(getGetACategoryUrl(categoryId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getACategoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getACategoryResponse
}




export const getGetACategoryKey = (categoryId: string,
    params?: GetACategoryParams,) => [`https://api.spotify.com/v1/browse/categories/${categoryId}`, ...(params ? [params]: [])] as const;

export type GetACategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getACategory>>>

/**
 * @summary Get Single Browse Category

 */
export const useGetACategory = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  categoryId: string,
    params?: GetACategoryParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getACategory>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(categoryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetACategoryKey(categoryId,params) : null);
  const swrFn = () => getACategory(categoryId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
