/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AddTracksToPlaylistBody,
  AddTracksToPlaylistParams,
  ArrayOfImagesResponse,
  ChangePlaylistDetailsBody,
  CreatePlaylistBody,
  ForbiddenResponse,
  GetACategoriesPlaylistsParams,
  GetAListOfCurrentUsersPlaylistsParams,
  GetFeaturedPlaylistsParams,
  GetListUsersPlaylistsParams,
  GetPlaylistParams,
  GetPlaylistsTracksParams,
  OnePlaylistResponse,
  PagedFeaturedPlaylistsResponse,
  PagedPlaylistsResponse,
  PagingPlaylistTrackObjectResponse,
  PlaylistSnapshotIdResponse,
  RemoveTracksPlaylistBody,
  ReorderOrReplacePlaylistsTracksBody,
  ReorderOrReplacePlaylistsTracksParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get a playlist owned by a Spotify user.

 * @summary Get Playlist

 */
export type getPlaylistResponse200 = {
  data: OnePlaylistResponse
  status: 200
}

export type getPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getPlaylistResponseSuccess = (getPlaylistResponse200) & {
  headers: Headers;
};
export type getPlaylistResponseError = (getPlaylistResponse401 | getPlaylistResponse403 | getPlaylistResponse429) & {
  headers: Headers;
};

export type getPlaylistResponse = (getPlaylistResponseSuccess | getPlaylistResponseError)

export const getGetPlaylistUrl = (playlistId: string,
    params?: GetPlaylistParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/playlists/${playlistId}?${stringifiedParams}` : `https://api.spotify.com/v1/playlists/${playlistId}`
}

export const getPlaylist = async (playlistId: string,
    params?: GetPlaylistParams, options?: RequestInit): Promise<getPlaylistResponse> => {
  
  const res = await fetch(getGetPlaylistUrl(playlistId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPlaylistResponse
}




export const getGetPlaylistKey = (playlistId: string,
    params?: GetPlaylistParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}`, ...(params ? [params]: [])] as const;

export type GetPlaylistQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaylist>>>

/**
 * @summary Get Playlist

 */
export const useGetPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params?: GetPlaylistParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getPlaylist>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(playlistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetPlaylistKey(playlistId,params) : null);
  const swrFn = () => getPlaylist(playlistId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Change a playlist's name and public/private state. (The user must, of
course, own the playlist.)

 * @summary Change Playlist Details

 */
export type changePlaylistDetailsResponse200 = {
  data: void
  status: 200
}

export type changePlaylistDetailsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type changePlaylistDetailsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type changePlaylistDetailsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type changePlaylistDetailsResponseSuccess = (changePlaylistDetailsResponse200) & {
  headers: Headers;
};
export type changePlaylistDetailsResponseError = (changePlaylistDetailsResponse401 | changePlaylistDetailsResponse403 | changePlaylistDetailsResponse429) & {
  headers: Headers;
};

export type changePlaylistDetailsResponse = (changePlaylistDetailsResponseSuccess | changePlaylistDetailsResponseError)

export const getChangePlaylistDetailsUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}`
}

export const changePlaylistDetails = async (playlistId: string,
    changePlaylistDetailsBody: ChangePlaylistDetailsBody, options?: RequestInit): Promise<changePlaylistDetailsResponse> => {
  
  const res = await fetch(getChangePlaylistDetailsUrl(playlistId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePlaylistDetailsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: changePlaylistDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as changePlaylistDetailsResponse
}




export const getChangePlaylistDetailsMutationFetcher = (playlistId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ChangePlaylistDetailsBody }) => {
    return changePlaylistDetails(playlistId, arg, options);
  }
}
export const getChangePlaylistDetailsMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}`] as const;

export type ChangePlaylistDetailsMutationResult = NonNullable<Awaited<ReturnType<typeof changePlaylistDetails>>>

/**
 * @summary Change Playlist Details

 */
export const useChangePlaylistDetails = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof changePlaylistDetails>>, TError, Key, ChangePlaylistDetailsBody, Awaited<ReturnType<typeof changePlaylistDetails>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getChangePlaylistDetailsMutationKey(playlistId);
  const swrFn = getChangePlaylistDetailsMutationFetcher(playlistId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get full details of the items of a playlist owned by a Spotify user.

 * @summary Get Playlist Items

 */
export type getPlaylistsTracksResponse200 = {
  data: PagingPlaylistTrackObjectResponse
  status: 200
}

export type getPlaylistsTracksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPlaylistsTracksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getPlaylistsTracksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getPlaylistsTracksResponseSuccess = (getPlaylistsTracksResponse200) & {
  headers: Headers;
};
export type getPlaylistsTracksResponseError = (getPlaylistsTracksResponse401 | getPlaylistsTracksResponse403 | getPlaylistsTracksResponse429) & {
  headers: Headers;
};

export type getPlaylistsTracksResponse = (getPlaylistsTracksResponseSuccess | getPlaylistsTracksResponseError)

export const getGetPlaylistsTracksUrl = (playlistId: string,
    params?: GetPlaylistsTracksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/playlists/${playlistId}/tracks?${stringifiedParams}` : `https://api.spotify.com/v1/playlists/${playlistId}/tracks`
}

export const getPlaylistsTracks = async (playlistId: string,
    params?: GetPlaylistsTracksParams, options?: RequestInit): Promise<getPlaylistsTracksResponse> => {
  
  const res = await fetch(getGetPlaylistsTracksUrl(playlistId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPlaylistsTracksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPlaylistsTracksResponse
}




export const getGetPlaylistsTracksKey = (playlistId: string,
    params?: GetPlaylistsTracksParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, ...(params ? [params]: [])] as const;

export type GetPlaylistsTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaylistsTracks>>>

/**
 * @summary Get Playlist Items

 */
export const useGetPlaylistsTracks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params?: GetPlaylistsTracksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getPlaylistsTracks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(playlistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetPlaylistsTracksKey(playlistId,params) : null);
  const swrFn = () => getPlaylistsTracks(playlistId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Add one or more items to a user's playlist.

 * @summary Add Items to Playlist

 */
export type addTracksToPlaylistResponse201 = {
  data: PlaylistSnapshotIdResponse
  status: 201
}

export type addTracksToPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type addTracksToPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type addTracksToPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type addTracksToPlaylistResponseSuccess = (addTracksToPlaylistResponse201) & {
  headers: Headers;
};
export type addTracksToPlaylistResponseError = (addTracksToPlaylistResponse401 | addTracksToPlaylistResponse403 | addTracksToPlaylistResponse429) & {
  headers: Headers;
};

export type addTracksToPlaylistResponse = (addTracksToPlaylistResponseSuccess | addTracksToPlaylistResponseError)

export const getAddTracksToPlaylistUrl = (playlistId: string,
    params?: AddTracksToPlaylistParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/playlists/${playlistId}/tracks?${stringifiedParams}` : `https://api.spotify.com/v1/playlists/${playlistId}/tracks`
}

export const addTracksToPlaylist = async (playlistId: string,
    addTracksToPlaylistBody: AddTracksToPlaylistBody,
    params?: AddTracksToPlaylistParams, options?: RequestInit): Promise<addTracksToPlaylistResponse> => {
  
  const res = await fetch(getAddTracksToPlaylistUrl(playlistId,params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addTracksToPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addTracksToPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addTracksToPlaylistResponse
}




export const getAddTracksToPlaylistMutationFetcher = (playlistId: string,
    params?: AddTracksToPlaylistParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: AddTracksToPlaylistBody }) => {
    return addTracksToPlaylist(playlistId, arg, params, options);
  }
}
export const getAddTracksToPlaylistMutationKey = (playlistId: string,
    params?: AddTracksToPlaylistParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, ...(params ? [params]: [])] as const;

export type AddTracksToPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof addTracksToPlaylist>>>

/**
 * @summary Add Items to Playlist

 */
export const useAddTracksToPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params?: AddTracksToPlaylistParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addTracksToPlaylist>>, TError, Key, AddTracksToPlaylistBody, Awaited<ReturnType<typeof addTracksToPlaylist>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddTracksToPlaylistMutationKey(playlistId,params);
  const swrFn = getAddTracksToPlaylistMutationFetcher(playlistId,params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Either reorder or replace items in a playlist depending on the request's parameters.
To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
To replace items, include `uris` as either a query parameter or in the request's body.
Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.
<br/>
**Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
These operations can't be applied together in a single request.

 * @summary Update Playlist Items

 */
export type reorderOrReplacePlaylistsTracksResponse200 = {
  data: PlaylistSnapshotIdResponse
  status: 200
}

export type reorderOrReplacePlaylistsTracksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type reorderOrReplacePlaylistsTracksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type reorderOrReplacePlaylistsTracksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type reorderOrReplacePlaylistsTracksResponseSuccess = (reorderOrReplacePlaylistsTracksResponse200) & {
  headers: Headers;
};
export type reorderOrReplacePlaylistsTracksResponseError = (reorderOrReplacePlaylistsTracksResponse401 | reorderOrReplacePlaylistsTracksResponse403 | reorderOrReplacePlaylistsTracksResponse429) & {
  headers: Headers;
};

export type reorderOrReplacePlaylistsTracksResponse = (reorderOrReplacePlaylistsTracksResponseSuccess | reorderOrReplacePlaylistsTracksResponseError)

export const getReorderOrReplacePlaylistsTracksUrl = (playlistId: string,
    params?: ReorderOrReplacePlaylistsTracksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/playlists/${playlistId}/tracks?${stringifiedParams}` : `https://api.spotify.com/v1/playlists/${playlistId}/tracks`
}

export const reorderOrReplacePlaylistsTracks = async (playlistId: string,
    reorderOrReplacePlaylistsTracksBody: ReorderOrReplacePlaylistsTracksBody,
    params?: ReorderOrReplacePlaylistsTracksParams, options?: RequestInit): Promise<reorderOrReplacePlaylistsTracksResponse> => {
  
  const res = await fetch(getReorderOrReplacePlaylistsTracksUrl(playlistId,params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reorderOrReplacePlaylistsTracksBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: reorderOrReplacePlaylistsTracksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as reorderOrReplacePlaylistsTracksResponse
}




export const getReorderOrReplacePlaylistsTracksMutationFetcher = (playlistId: string,
    params?: ReorderOrReplacePlaylistsTracksParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ReorderOrReplacePlaylistsTracksBody }) => {
    return reorderOrReplacePlaylistsTracks(playlistId, arg, params, options);
  }
}
export const getReorderOrReplacePlaylistsTracksMutationKey = (playlistId: string,
    params?: ReorderOrReplacePlaylistsTracksParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, ...(params ? [params]: [])] as const;

export type ReorderOrReplacePlaylistsTracksMutationResult = NonNullable<Awaited<ReturnType<typeof reorderOrReplacePlaylistsTracks>>>

/**
 * @summary Update Playlist Items

 */
export const useReorderOrReplacePlaylistsTracks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params?: ReorderOrReplacePlaylistsTracksParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof reorderOrReplacePlaylistsTracks>>, TError, Key, ReorderOrReplacePlaylistsTracksBody, Awaited<ReturnType<typeof reorderOrReplacePlaylistsTracks>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getReorderOrReplacePlaylistsTracksMutationKey(playlistId,params);
  const swrFn = getReorderOrReplacePlaylistsTracksMutationFetcher(playlistId,params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove one or more items from a user's playlist.

 * @summary Remove Playlist Items

 */
export type removeTracksPlaylistResponse200 = {
  data: PlaylistSnapshotIdResponse
  status: 200
}

export type removeTracksPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeTracksPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeTracksPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type removeTracksPlaylistResponseSuccess = (removeTracksPlaylistResponse200) & {
  headers: Headers;
};
export type removeTracksPlaylistResponseError = (removeTracksPlaylistResponse401 | removeTracksPlaylistResponse403 | removeTracksPlaylistResponse429) & {
  headers: Headers;
};

export type removeTracksPlaylistResponse = (removeTracksPlaylistResponseSuccess | removeTracksPlaylistResponseError)

export const getRemoveTracksPlaylistUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}/tracks`
}

export const removeTracksPlaylist = async (playlistId: string,
    removeTracksPlaylistBody: RemoveTracksPlaylistBody, options?: RequestInit): Promise<removeTracksPlaylistResponse> => {
  
  const res = await fetch(getRemoveTracksPlaylistUrl(playlistId),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeTracksPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeTracksPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeTracksPlaylistResponse
}




export const getRemoveTracksPlaylistMutationFetcher = (playlistId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RemoveTracksPlaylistBody }) => {
    return removeTracksPlaylist(playlistId, arg, options);
  }
}
export const getRemoveTracksPlaylistMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/tracks`] as const;

export type RemoveTracksPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof removeTracksPlaylist>>>

/**
 * @summary Remove Playlist Items

 */
export const useRemoveTracksPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeTracksPlaylist>>, TError, Key, RemoveTracksPlaylistBody, Awaited<ReturnType<typeof removeTracksPlaylist>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveTracksPlaylistMutationKey(playlistId);
  const swrFn = getRemoveTracksPlaylistMutationFetcher(playlistId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of the playlists owned or followed by the current Spotify
user.

 * @summary Get Current User's Playlists

 */
export type getAListOfCurrentUsersPlaylistsResponse200 = {
  data: PagedPlaylistsResponse
  status: 200
}

export type getAListOfCurrentUsersPlaylistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAListOfCurrentUsersPlaylistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAListOfCurrentUsersPlaylistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAListOfCurrentUsersPlaylistsResponseSuccess = (getAListOfCurrentUsersPlaylistsResponse200) & {
  headers: Headers;
};
export type getAListOfCurrentUsersPlaylistsResponseError = (getAListOfCurrentUsersPlaylistsResponse401 | getAListOfCurrentUsersPlaylistsResponse403 | getAListOfCurrentUsersPlaylistsResponse429) & {
  headers: Headers;
};

export type getAListOfCurrentUsersPlaylistsResponse = (getAListOfCurrentUsersPlaylistsResponseSuccess | getAListOfCurrentUsersPlaylistsResponseError)

export const getGetAListOfCurrentUsersPlaylistsUrl = (params?: GetAListOfCurrentUsersPlaylistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/playlists?${stringifiedParams}` : `https://api.spotify.com/v1/me/playlists`
}

export const getAListOfCurrentUsersPlaylists = async (params?: GetAListOfCurrentUsersPlaylistsParams, options?: RequestInit): Promise<getAListOfCurrentUsersPlaylistsResponse> => {
  
  const res = await fetch(getGetAListOfCurrentUsersPlaylistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAListOfCurrentUsersPlaylistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAListOfCurrentUsersPlaylistsResponse
}




export const getGetAListOfCurrentUsersPlaylistsKey = (params?: GetAListOfCurrentUsersPlaylistsParams,) => [`https://api.spotify.com/v1/me/playlists`, ...(params ? [params]: [])] as const;

export type GetAListOfCurrentUsersPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof getAListOfCurrentUsersPlaylists>>>

/**
 * @summary Get Current User's Playlists

 */
export const useGetAListOfCurrentUsersPlaylists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetAListOfCurrentUsersPlaylistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAListOfCurrentUsersPlaylists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAListOfCurrentUsersPlaylistsKey(params) : null);
  const swrFn = () => getAListOfCurrentUsersPlaylists(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of the playlists owned or followed by a Spotify user.

 * @summary Get User's Playlists

 */
export type getListUsersPlaylistsResponse200 = {
  data: PagedPlaylistsResponse
  status: 200
}

export type getListUsersPlaylistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getListUsersPlaylistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getListUsersPlaylistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getListUsersPlaylistsResponseSuccess = (getListUsersPlaylistsResponse200) & {
  headers: Headers;
};
export type getListUsersPlaylistsResponseError = (getListUsersPlaylistsResponse401 | getListUsersPlaylistsResponse403 | getListUsersPlaylistsResponse429) & {
  headers: Headers;
};

export type getListUsersPlaylistsResponse = (getListUsersPlaylistsResponseSuccess | getListUsersPlaylistsResponseError)

export const getGetListUsersPlaylistsUrl = (userId: string,
    params?: GetListUsersPlaylistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/users/${userId}/playlists?${stringifiedParams}` : `https://api.spotify.com/v1/users/${userId}/playlists`
}

export const getListUsersPlaylists = async (userId: string,
    params?: GetListUsersPlaylistsParams, options?: RequestInit): Promise<getListUsersPlaylistsResponse> => {
  
  const res = await fetch(getGetListUsersPlaylistsUrl(userId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getListUsersPlaylistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getListUsersPlaylistsResponse
}




export const getGetListUsersPlaylistsKey = (userId: string,
    params?: GetListUsersPlaylistsParams,) => [`https://api.spotify.com/v1/users/${userId}/playlists`, ...(params ? [params]: [])] as const;

export type GetListUsersPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof getListUsersPlaylists>>>

/**
 * @summary Get User's Playlists

 */
export const useGetListUsersPlaylists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  userId: string,
    params?: GetListUsersPlaylistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getListUsersPlaylists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(userId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetListUsersPlaylistsKey(userId,params) : null);
  const swrFn = () => getListUsersPlaylists(userId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Create a playlist for a Spotify user. (The playlist will be empty until
you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)
Each user is generally limited to a maximum of 11000 playlists.

 * @summary Create Playlist

 */
export type createPlaylistResponse201 = {
  data: OnePlaylistResponse
  status: 201
}

export type createPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type createPlaylistResponseSuccess = (createPlaylistResponse201) & {
  headers: Headers;
};
export type createPlaylistResponseError = (createPlaylistResponse401 | createPlaylistResponse403 | createPlaylistResponse429) & {
  headers: Headers;
};

export type createPlaylistResponse = (createPlaylistResponseSuccess | createPlaylistResponseError)

export const getCreatePlaylistUrl = (userId: string,) => {


  

  return `https://api.spotify.com/v1/users/${userId}/playlists`
}

export const createPlaylist = async (userId: string,
    createPlaylistBody: CreatePlaylistBody, options?: RequestInit): Promise<createPlaylistResponse> => {
  
  const res = await fetch(getCreatePlaylistUrl(userId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPlaylistResponse
}




export const getCreatePlaylistMutationFetcher = (userId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreatePlaylistBody }) => {
    return createPlaylist(userId, arg, options);
  }
}
export const getCreatePlaylistMutationKey = (userId: string,) => [`https://api.spotify.com/v1/users/${userId}/playlists`] as const;

export type CreatePlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof createPlaylist>>>

/**
 * @summary Create Playlist

 */
export const useCreatePlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  userId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createPlaylist>>, TError, Key, CreatePlaylistBody, Awaited<ReturnType<typeof createPlaylist>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreatePlaylistMutationKey(userId);
  const swrFn = getCreatePlaylistMutationFetcher(userId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).

 * @summary Get Featured Playlists

 */
export type getFeaturedPlaylistsResponse200 = {
  data: PagedFeaturedPlaylistsResponse
  status: 200
}

export type getFeaturedPlaylistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getFeaturedPlaylistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getFeaturedPlaylistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getFeaturedPlaylistsResponseSuccess = (getFeaturedPlaylistsResponse200) & {
  headers: Headers;
};
export type getFeaturedPlaylistsResponseError = (getFeaturedPlaylistsResponse401 | getFeaturedPlaylistsResponse403 | getFeaturedPlaylistsResponse429) & {
  headers: Headers;
};

export type getFeaturedPlaylistsResponse = (getFeaturedPlaylistsResponseSuccess | getFeaturedPlaylistsResponseError)

export const getGetFeaturedPlaylistsUrl = (params?: GetFeaturedPlaylistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/browse/featured-playlists?${stringifiedParams}` : `https://api.spotify.com/v1/browse/featured-playlists`
}

export const getFeaturedPlaylists = async (params?: GetFeaturedPlaylistsParams, options?: RequestInit): Promise<getFeaturedPlaylistsResponse> => {
  
  const res = await fetch(getGetFeaturedPlaylistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getFeaturedPlaylistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getFeaturedPlaylistsResponse
}




export const getGetFeaturedPlaylistsKey = (params?: GetFeaturedPlaylistsParams,) => [`https://api.spotify.com/v1/browse/featured-playlists`, ...(params ? [params]: [])] as const;

export type GetFeaturedPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof getFeaturedPlaylists>>>

/**
 * @summary Get Featured Playlists

 */
export const useGetFeaturedPlaylists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetFeaturedPlaylistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFeaturedPlaylists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFeaturedPlaylistsKey(params) : null);
  const swrFn = () => getFeaturedPlaylists(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of Spotify playlists tagged with a particular category.

 * @summary Get Category's Playlists

 */
export type getACategoriesPlaylistsResponse200 = {
  data: PagedFeaturedPlaylistsResponse
  status: 200
}

export type getACategoriesPlaylistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getACategoriesPlaylistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getACategoriesPlaylistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getACategoriesPlaylistsResponseSuccess = (getACategoriesPlaylistsResponse200) & {
  headers: Headers;
};
export type getACategoriesPlaylistsResponseError = (getACategoriesPlaylistsResponse401 | getACategoriesPlaylistsResponse403 | getACategoriesPlaylistsResponse429) & {
  headers: Headers;
};

export type getACategoriesPlaylistsResponse = (getACategoriesPlaylistsResponseSuccess | getACategoriesPlaylistsResponseError)

export const getGetACategoriesPlaylistsUrl = (categoryId: string,
    params?: GetACategoriesPlaylistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/browse/categories/${categoryId}/playlists?${stringifiedParams}` : `https://api.spotify.com/v1/browse/categories/${categoryId}/playlists`
}

export const getACategoriesPlaylists = async (categoryId: string,
    params?: GetACategoriesPlaylistsParams, options?: RequestInit): Promise<getACategoriesPlaylistsResponse> => {
  
  const res = await fetch(getGetACategoriesPlaylistsUrl(categoryId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getACategoriesPlaylistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getACategoriesPlaylistsResponse
}




export const getGetACategoriesPlaylistsKey = (categoryId: string,
    params?: GetACategoriesPlaylistsParams,) => [`https://api.spotify.com/v1/browse/categories/${categoryId}/playlists`, ...(params ? [params]: [])] as const;

export type GetACategoriesPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof getACategoriesPlaylists>>>

/**
 * @summary Get Category's Playlists

 */
export const useGetACategoriesPlaylists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  categoryId: string,
    params?: GetACategoriesPlaylistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getACategoriesPlaylists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(categoryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetACategoriesPlaylistsKey(categoryId,params) : null);
  const swrFn = () => getACategoriesPlaylists(categoryId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current image associated with a specific playlist.

 * @summary Get Playlist Cover Image

 */
export type getPlaylistCoverResponse200 = {
  data: ArrayOfImagesResponse
  status: 200
}

export type getPlaylistCoverResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPlaylistCoverResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getPlaylistCoverResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getPlaylistCoverResponseSuccess = (getPlaylistCoverResponse200) & {
  headers: Headers;
};
export type getPlaylistCoverResponseError = (getPlaylistCoverResponse401 | getPlaylistCoverResponse403 | getPlaylistCoverResponse429) & {
  headers: Headers;
};

export type getPlaylistCoverResponse = (getPlaylistCoverResponseSuccess | getPlaylistCoverResponseError)

export const getGetPlaylistCoverUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}/images`
}

export const getPlaylistCover = async (playlistId: string, options?: RequestInit): Promise<getPlaylistCoverResponse> => {
  
  const res = await fetch(getGetPlaylistCoverUrl(playlistId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPlaylistCoverResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPlaylistCoverResponse
}




export const getGetPlaylistCoverKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/images`] as const;

export type GetPlaylistCoverQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaylistCover>>>

/**
 * @summary Get Playlist Cover Image

 */
export const useGetPlaylistCover = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getPlaylistCover>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(playlistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetPlaylistCoverKey(playlistId) : null);
  const swrFn = () => getPlaylistCover(playlistId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Replace the image used to represent a specific playlist.

 * @summary Add Custom Playlist Cover Image

 */
export type uploadCustomPlaylistCoverResponse202 = {
  data: void
  status: 202
}

export type uploadCustomPlaylistCoverResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type uploadCustomPlaylistCoverResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type uploadCustomPlaylistCoverResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type uploadCustomPlaylistCoverResponseSuccess = (uploadCustomPlaylistCoverResponse202) & {
  headers: Headers;
};
export type uploadCustomPlaylistCoverResponseError = (uploadCustomPlaylistCoverResponse401 | uploadCustomPlaylistCoverResponse403 | uploadCustomPlaylistCoverResponse429) & {
  headers: Headers;
};

export type uploadCustomPlaylistCoverResponse = (uploadCustomPlaylistCoverResponseSuccess | uploadCustomPlaylistCoverResponseError)

export const getUploadCustomPlaylistCoverUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}/images`
}

export const uploadCustomPlaylistCover = async (playlistId: string,
    uploadCustomPlaylistCoverBody: Blob, options?: RequestInit): Promise<uploadCustomPlaylistCoverResponse> => {
  
  const res = await fetch(getUploadCustomPlaylistCoverUrl(playlistId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'image/jpeg', ...options?.headers },
    body: JSON.stringify(
      uploadCustomPlaylistCoverBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadCustomPlaylistCoverResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadCustomPlaylistCoverResponse
}




export const getUploadCustomPlaylistCoverMutationFetcher = (playlistId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: Blob }) => {
    return uploadCustomPlaylistCover(playlistId, arg, options);
  }
}
export const getUploadCustomPlaylistCoverMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/images`] as const;

export type UploadCustomPlaylistCoverMutationResult = NonNullable<Awaited<ReturnType<typeof uploadCustomPlaylistCover>>>

/**
 * @summary Add Custom Playlist Cover Image

 */
export const useUploadCustomPlaylistCover = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof uploadCustomPlaylistCover>>, TError, Key, Blob, Awaited<ReturnType<typeof uploadCustomPlaylistCover>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUploadCustomPlaylistCoverMutationKey(playlistId);
  const swrFn = getUploadCustomPlaylistCoverMutationFetcher(playlistId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
