/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ArrayOfBooleansResponse,
  CheckUsersSavedShowsParams,
  ForbiddenResponse,
  GetAShowParams,
  GetAShowsEpisodesParams,
  GetMultipleShowsParams,
  GetUsersSavedShowsParams,
  ManySimplifiedShowsResponse,
  OneShowResponse,
  PagingSavedShowObjectResponse,
  PagingSimplifiedEpisodeObjectResponse,
  RemoveShowsUserBody,
  RemoveShowsUserParams,
  SaveShowsUserBody,
  SaveShowsUserParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single show identified by its
unique Spotify ID.

 * @summary Get Show

 */
export type getAShowResponse200 = {
  data: OneShowResponse
  status: 200
}

export type getAShowResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAShowResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAShowResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAShowResponseSuccess = (getAShowResponse200) & {
  headers: Headers;
};
export type getAShowResponseError = (getAShowResponse401 | getAShowResponse403 | getAShowResponse429) & {
  headers: Headers;
};

export type getAShowResponse = (getAShowResponseSuccess | getAShowResponseError)

export const getGetAShowUrl = (id: string,
    params?: GetAShowParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/shows/${id}?${stringifiedParams}` : `https://api.spotify.com/v1/shows/${id}`
}

export const getAShow = async (id: string,
    params?: GetAShowParams, options?: RequestInit): Promise<getAShowResponse> => {
  
  const res = await fetch(getGetAShowUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAShowResponse
}




export const getGetAShowKey = (id: string,
    params?: GetAShowParams,) => [`https://api.spotify.com/v1/shows/${id}`, ...(params ? [params]: [])] as const;

export type GetAShowQueryResult = NonNullable<Awaited<ReturnType<typeof getAShow>>>

/**
 * @summary Get Show

 */
export const useGetAShow = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAShowParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAShow>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAShowKey(id,params) : null);
  const swrFn = () => getAShow(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for several shows based on their Spotify IDs.

 * @summary Get Several Shows

 */
export type getMultipleShowsResponse200 = {
  data: ManySimplifiedShowsResponse
  status: 200
}

export type getMultipleShowsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMultipleShowsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMultipleShowsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getMultipleShowsResponseSuccess = (getMultipleShowsResponse200) & {
  headers: Headers;
};
export type getMultipleShowsResponseError = (getMultipleShowsResponse401 | getMultipleShowsResponse403 | getMultipleShowsResponse429) & {
  headers: Headers;
};

export type getMultipleShowsResponse = (getMultipleShowsResponseSuccess | getMultipleShowsResponseError)

export const getGetMultipleShowsUrl = (params: GetMultipleShowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/shows?${stringifiedParams}` : `https://api.spotify.com/v1/shows`
}

export const getMultipleShows = async (params: GetMultipleShowsParams, options?: RequestInit): Promise<getMultipleShowsResponse> => {
  
  const res = await fetch(getGetMultipleShowsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMultipleShowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMultipleShowsResponse
}




export const getGetMultipleShowsKey = (params: GetMultipleShowsParams,) => [`https://api.spotify.com/v1/shows`, ...(params ? [params]: [])] as const;

export type GetMultipleShowsQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleShows>>>

/**
 * @summary Get Several Shows

 */
export const useGetMultipleShows = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetMultipleShowsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMultipleShows>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMultipleShowsKey(params) : null);
  const swrFn = () => getMultipleShows(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.

 * @summary Get Show Episodes

 */
export type getAShowsEpisodesResponse200 = {
  data: PagingSimplifiedEpisodeObjectResponse
  status: 200
}

export type getAShowsEpisodesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAShowsEpisodesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAShowsEpisodesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAShowsEpisodesResponseSuccess = (getAShowsEpisodesResponse200) & {
  headers: Headers;
};
export type getAShowsEpisodesResponseError = (getAShowsEpisodesResponse401 | getAShowsEpisodesResponse403 | getAShowsEpisodesResponse429) & {
  headers: Headers;
};

export type getAShowsEpisodesResponse = (getAShowsEpisodesResponseSuccess | getAShowsEpisodesResponseError)

export const getGetAShowsEpisodesUrl = (id: string,
    params?: GetAShowsEpisodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/shows/${id}/episodes?${stringifiedParams}` : `https://api.spotify.com/v1/shows/${id}/episodes`
}

export const getAShowsEpisodes = async (id: string,
    params?: GetAShowsEpisodesParams, options?: RequestInit): Promise<getAShowsEpisodesResponse> => {
  
  const res = await fetch(getGetAShowsEpisodesUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAShowsEpisodesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAShowsEpisodesResponse
}




export const getGetAShowsEpisodesKey = (id: string,
    params?: GetAShowsEpisodesParams,) => [`https://api.spotify.com/v1/shows/${id}/episodes`, ...(params ? [params]: [])] as const;

export type GetAShowsEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof getAShowsEpisodes>>>

/**
 * @summary Get Show Episodes

 */
export const useGetAShowsEpisodes = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAShowsEpisodesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAShowsEpisodes>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAShowsEpisodesKey(id,params) : null);
  const swrFn = () => getAShowsEpisodes(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.

 * @summary Get User's Saved Shows

 */
export type getUsersSavedShowsResponse200 = {
  data: PagingSavedShowObjectResponse
  status: 200
}

export type getUsersSavedShowsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersSavedShowsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersSavedShowsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersSavedShowsResponseSuccess = (getUsersSavedShowsResponse200) & {
  headers: Headers;
};
export type getUsersSavedShowsResponseError = (getUsersSavedShowsResponse401 | getUsersSavedShowsResponse403 | getUsersSavedShowsResponse429) & {
  headers: Headers;
};

export type getUsersSavedShowsResponse = (getUsersSavedShowsResponseSuccess | getUsersSavedShowsResponseError)

export const getGetUsersSavedShowsUrl = (params?: GetUsersSavedShowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/shows?${stringifiedParams}` : `https://api.spotify.com/v1/me/shows`
}

export const getUsersSavedShows = async (params?: GetUsersSavedShowsParams, options?: RequestInit): Promise<getUsersSavedShowsResponse> => {
  
  const res = await fetch(getGetUsersSavedShowsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersSavedShowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersSavedShowsResponse
}




export const getGetUsersSavedShowsKey = (params?: GetUsersSavedShowsParams,) => [`https://api.spotify.com/v1/me/shows`, ...(params ? [params]: [])] as const;

export type GetUsersSavedShowsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersSavedShows>>>

/**
 * @summary Get User's Saved Shows

 */
export const useGetUsersSavedShows = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersSavedShowsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersSavedShows>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersSavedShowsKey(params) : null);
  const swrFn = () => getUsersSavedShows(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Save one or more shows to current Spotify user's library.

 * @summary Save Shows for Current User

 */
export type saveShowsUserResponse200 = {
  data: void
  status: 200
}

export type saveShowsUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type saveShowsUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type saveShowsUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type saveShowsUserResponseSuccess = (saveShowsUserResponse200) & {
  headers: Headers;
};
export type saveShowsUserResponseError = (saveShowsUserResponse401 | saveShowsUserResponse403 | saveShowsUserResponse429) & {
  headers: Headers;
};

export type saveShowsUserResponse = (saveShowsUserResponseSuccess | saveShowsUserResponseError)

export const getSaveShowsUserUrl = (params: SaveShowsUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/shows?${stringifiedParams}` : `https://api.spotify.com/v1/me/shows`
}

export const saveShowsUser = async (saveShowsUserBody: SaveShowsUserBody,
    params: SaveShowsUserParams, options?: RequestInit): Promise<saveShowsUserResponse> => {
  
  const res = await fetch(getSaveShowsUserUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveShowsUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: saveShowsUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveShowsUserResponse
}




export const getSaveShowsUserMutationFetcher = (params: SaveShowsUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: SaveShowsUserBody }) => {
    return saveShowsUser(arg, params, options);
  }
}
export const getSaveShowsUserMutationKey = (params: SaveShowsUserParams,) => [`https://api.spotify.com/v1/me/shows`, ...(params ? [params]: [])] as const;

export type SaveShowsUserMutationResult = NonNullable<Awaited<ReturnType<typeof saveShowsUser>>>

/**
 * @summary Save Shows for Current User

 */
export const useSaveShowsUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: SaveShowsUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof saveShowsUser>>, TError, Key, SaveShowsUserBody, Awaited<ReturnType<typeof saveShowsUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSaveShowsUserMutationKey(params);
  const swrFn = getSaveShowsUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Delete one or more shows from current Spotify user's library.

 * @summary Remove User's Saved Shows

 */
export type removeShowsUserResponse200 = {
  data: void
  status: 200
}

export type removeShowsUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeShowsUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeShowsUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type removeShowsUserResponseSuccess = (removeShowsUserResponse200) & {
  headers: Headers;
};
export type removeShowsUserResponseError = (removeShowsUserResponse401 | removeShowsUserResponse403 | removeShowsUserResponse429) & {
  headers: Headers;
};

export type removeShowsUserResponse = (removeShowsUserResponseSuccess | removeShowsUserResponseError)

export const getRemoveShowsUserUrl = (params: RemoveShowsUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/shows?${stringifiedParams}` : `https://api.spotify.com/v1/me/shows`
}

export const removeShowsUser = async (removeShowsUserBody: RemoveShowsUserBody,
    params: RemoveShowsUserParams, options?: RequestInit): Promise<removeShowsUserResponse> => {
  
  const res = await fetch(getRemoveShowsUserUrl(params),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeShowsUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeShowsUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeShowsUserResponse
}




export const getRemoveShowsUserMutationFetcher = (params: RemoveShowsUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RemoveShowsUserBody }) => {
    return removeShowsUser(arg, params, options);
  }
}
export const getRemoveShowsUserMutationKey = (params: RemoveShowsUserParams,) => [`https://api.spotify.com/v1/me/shows`, ...(params ? [params]: [])] as const;

export type RemoveShowsUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeShowsUser>>>

/**
 * @summary Remove User's Saved Shows

 */
export const useRemoveShowsUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: RemoveShowsUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeShowsUser>>, TError, Key, RemoveShowsUserBody, Awaited<ReturnType<typeof removeShowsUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveShowsUserMutationKey(params);
  const swrFn = getRemoveShowsUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check if one or more shows is already saved in the current Spotify user's library.

 * @summary Check User's Saved Shows

 */
export type checkUsersSavedShowsResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkUsersSavedShowsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkUsersSavedShowsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkUsersSavedShowsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkUsersSavedShowsResponseSuccess = (checkUsersSavedShowsResponse200) & {
  headers: Headers;
};
export type checkUsersSavedShowsResponseError = (checkUsersSavedShowsResponse401 | checkUsersSavedShowsResponse403 | checkUsersSavedShowsResponse429) & {
  headers: Headers;
};

export type checkUsersSavedShowsResponse = (checkUsersSavedShowsResponseSuccess | checkUsersSavedShowsResponseError)

export const getCheckUsersSavedShowsUrl = (params: CheckUsersSavedShowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/shows/contains?${stringifiedParams}` : `https://api.spotify.com/v1/me/shows/contains`
}

export const checkUsersSavedShows = async (params: CheckUsersSavedShowsParams, options?: RequestInit): Promise<checkUsersSavedShowsResponse> => {
  
  const res = await fetch(getCheckUsersSavedShowsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkUsersSavedShowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkUsersSavedShowsResponse
}




export const getCheckUsersSavedShowsKey = (params: CheckUsersSavedShowsParams,) => [`https://api.spotify.com/v1/me/shows/contains`, ...(params ? [params]: [])] as const;

export type CheckUsersSavedShowsQueryResult = NonNullable<Awaited<ReturnType<typeof checkUsersSavedShows>>>

/**
 * @summary Check User's Saved Shows

 */
export const useCheckUsersSavedShows = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckUsersSavedShowsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkUsersSavedShows>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckUsersSavedShowsKey(params) : null);
  const swrFn = () => checkUsersSavedShows(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
