/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ArrayOfBooleansResponse,
  CheckUsersSavedEpisodesParams,
  ForbiddenResponse,
  GetAnEpisodeParams,
  GetMultipleEpisodesParams,
  GetUsersSavedEpisodesParams,
  ManyEpisodesResponse,
  OneEpisodeResponse,
  PagingSavedEpisodeObjectResponse,
  RemoveEpisodesUserBody,
  RemoveEpisodesUserParams,
  SaveEpisodesUserBody,
  SaveEpisodesUserParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single episode identified by its
unique Spotify ID.

 * @summary Get Episode

 */
export type getAnEpisodeResponse200 = {
  data: OneEpisodeResponse
  status: 200
}

export type getAnEpisodeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnEpisodeResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnEpisodeResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnEpisodeResponseSuccess = (getAnEpisodeResponse200) & {
  headers: Headers;
};
export type getAnEpisodeResponseError = (getAnEpisodeResponse401 | getAnEpisodeResponse403 | getAnEpisodeResponse429) & {
  headers: Headers;
};

export type getAnEpisodeResponse = (getAnEpisodeResponseSuccess | getAnEpisodeResponseError)

export const getGetAnEpisodeUrl = (id: string,
    params?: GetAnEpisodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/episodes/${id}?${stringifiedParams}` : `https://api.spotify.com/v1/episodes/${id}`
}

export const getAnEpisode = async (id: string,
    params?: GetAnEpisodeParams, options?: RequestInit): Promise<getAnEpisodeResponse> => {
  
  const res = await fetch(getGetAnEpisodeUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnEpisodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnEpisodeResponse
}




export const getGetAnEpisodeKey = (id: string,
    params?: GetAnEpisodeParams,) => [`https://api.spotify.com/v1/episodes/${id}`, ...(params ? [params]: [])] as const;

export type GetAnEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof getAnEpisode>>>

/**
 * @summary Get Episode

 */
export const useGetAnEpisode = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnEpisodeParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnEpisode>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnEpisodeKey(id,params) : null);
  const swrFn = () => getAnEpisode(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for several episodes based on their Spotify IDs.

 * @summary Get Several Episodes

 */
export type getMultipleEpisodesResponse200 = {
  data: ManyEpisodesResponse
  status: 200
}

export type getMultipleEpisodesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMultipleEpisodesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMultipleEpisodesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getMultipleEpisodesResponseSuccess = (getMultipleEpisodesResponse200) & {
  headers: Headers;
};
export type getMultipleEpisodesResponseError = (getMultipleEpisodesResponse401 | getMultipleEpisodesResponse403 | getMultipleEpisodesResponse429) & {
  headers: Headers;
};

export type getMultipleEpisodesResponse = (getMultipleEpisodesResponseSuccess | getMultipleEpisodesResponseError)

export const getGetMultipleEpisodesUrl = (params: GetMultipleEpisodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/episodes?${stringifiedParams}` : `https://api.spotify.com/v1/episodes`
}

export const getMultipleEpisodes = async (params: GetMultipleEpisodesParams, options?: RequestInit): Promise<getMultipleEpisodesResponse> => {
  
  const res = await fetch(getGetMultipleEpisodesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMultipleEpisodesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMultipleEpisodesResponse
}




export const getGetMultipleEpisodesKey = (params: GetMultipleEpisodesParams,) => [`https://api.spotify.com/v1/episodes`, ...(params ? [params]: [])] as const;

export type GetMultipleEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleEpisodes>>>

/**
 * @summary Get Several Episodes

 */
export const useGetMultipleEpisodes = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetMultipleEpisodesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMultipleEpisodes>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMultipleEpisodesKey(params) : null);
  const swrFn = () => getMultipleEpisodes(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of the episodes saved in the current Spotify user's library.<br/>
This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).

 * @summary Get User's Saved Episodes

 */
export type getUsersSavedEpisodesResponse200 = {
  data: PagingSavedEpisodeObjectResponse
  status: 200
}

export type getUsersSavedEpisodesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersSavedEpisodesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersSavedEpisodesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersSavedEpisodesResponseSuccess = (getUsersSavedEpisodesResponse200) & {
  headers: Headers;
};
export type getUsersSavedEpisodesResponseError = (getUsersSavedEpisodesResponse401 | getUsersSavedEpisodesResponse403 | getUsersSavedEpisodesResponse429) & {
  headers: Headers;
};

export type getUsersSavedEpisodesResponse = (getUsersSavedEpisodesResponseSuccess | getUsersSavedEpisodesResponseError)

export const getGetUsersSavedEpisodesUrl = (params?: GetUsersSavedEpisodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/episodes?${stringifiedParams}` : `https://api.spotify.com/v1/me/episodes`
}

export const getUsersSavedEpisodes = async (params?: GetUsersSavedEpisodesParams, options?: RequestInit): Promise<getUsersSavedEpisodesResponse> => {
  
  const res = await fetch(getGetUsersSavedEpisodesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersSavedEpisodesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersSavedEpisodesResponse
}




export const getGetUsersSavedEpisodesKey = (params?: GetUsersSavedEpisodesParams,) => [`https://api.spotify.com/v1/me/episodes`, ...(params ? [params]: [])] as const;

export type GetUsersSavedEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersSavedEpisodes>>>

/**
 * @summary Get User's Saved Episodes

 */
export const useGetUsersSavedEpisodes = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersSavedEpisodesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersSavedEpisodes>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersSavedEpisodesKey(params) : null);
  const swrFn = () => getUsersSavedEpisodes(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Save one or more episodes to the current user's library.<br/>
This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).

 * @summary Save Episodes for Current User

 */
export type saveEpisodesUserResponse200 = {
  data: void
  status: 200
}

export type saveEpisodesUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type saveEpisodesUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type saveEpisodesUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type saveEpisodesUserResponseSuccess = (saveEpisodesUserResponse200) & {
  headers: Headers;
};
export type saveEpisodesUserResponseError = (saveEpisodesUserResponse401 | saveEpisodesUserResponse403 | saveEpisodesUserResponse429) & {
  headers: Headers;
};

export type saveEpisodesUserResponse = (saveEpisodesUserResponseSuccess | saveEpisodesUserResponseError)

export const getSaveEpisodesUserUrl = (params: SaveEpisodesUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/episodes?${stringifiedParams}` : `https://api.spotify.com/v1/me/episodes`
}

export const saveEpisodesUser = async (saveEpisodesUserBody: SaveEpisodesUserBody,
    params: SaveEpisodesUserParams, options?: RequestInit): Promise<saveEpisodesUserResponse> => {
  
  const res = await fetch(getSaveEpisodesUserUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveEpisodesUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: saveEpisodesUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveEpisodesUserResponse
}




export const getSaveEpisodesUserMutationFetcher = (params: SaveEpisodesUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: SaveEpisodesUserBody }) => {
    return saveEpisodesUser(arg, params, options);
  }
}
export const getSaveEpisodesUserMutationKey = (params: SaveEpisodesUserParams,) => [`https://api.spotify.com/v1/me/episodes`, ...(params ? [params]: [])] as const;

export type SaveEpisodesUserMutationResult = NonNullable<Awaited<ReturnType<typeof saveEpisodesUser>>>

/**
 * @summary Save Episodes for Current User

 */
export const useSaveEpisodesUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: SaveEpisodesUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof saveEpisodesUser>>, TError, Key, SaveEpisodesUserBody, Awaited<ReturnType<typeof saveEpisodesUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSaveEpisodesUserMutationKey(params);
  const swrFn = getSaveEpisodesUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove one or more episodes from the current user's library.<br/>
This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).

 * @summary Remove User's Saved Episodes

 */
export type removeEpisodesUserResponse200 = {
  data: void
  status: 200
}

export type removeEpisodesUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeEpisodesUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeEpisodesUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type removeEpisodesUserResponseSuccess = (removeEpisodesUserResponse200) & {
  headers: Headers;
};
export type removeEpisodesUserResponseError = (removeEpisodesUserResponse401 | removeEpisodesUserResponse403 | removeEpisodesUserResponse429) & {
  headers: Headers;
};

export type removeEpisodesUserResponse = (removeEpisodesUserResponseSuccess | removeEpisodesUserResponseError)

export const getRemoveEpisodesUserUrl = (params: RemoveEpisodesUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/episodes?${stringifiedParams}` : `https://api.spotify.com/v1/me/episodes`
}

export const removeEpisodesUser = async (removeEpisodesUserBody: RemoveEpisodesUserBody,
    params: RemoveEpisodesUserParams, options?: RequestInit): Promise<removeEpisodesUserResponse> => {
  
  const res = await fetch(getRemoveEpisodesUserUrl(params),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeEpisodesUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeEpisodesUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeEpisodesUserResponse
}




export const getRemoveEpisodesUserMutationFetcher = (params: RemoveEpisodesUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RemoveEpisodesUserBody }) => {
    return removeEpisodesUser(arg, params, options);
  }
}
export const getRemoveEpisodesUserMutationKey = (params: RemoveEpisodesUserParams,) => [`https://api.spotify.com/v1/me/episodes`, ...(params ? [params]: [])] as const;

export type RemoveEpisodesUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeEpisodesUser>>>

/**
 * @summary Remove User's Saved Episodes

 */
export const useRemoveEpisodesUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: RemoveEpisodesUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeEpisodesUser>>, TError, Key, RemoveEpisodesUserBody, Awaited<ReturnType<typeof removeEpisodesUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveEpisodesUserMutationKey(params);
  const swrFn = getRemoveEpisodesUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.<br/>
This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..

 * @summary Check User's Saved Episodes

 */
export type checkUsersSavedEpisodesResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkUsersSavedEpisodesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkUsersSavedEpisodesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkUsersSavedEpisodesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkUsersSavedEpisodesResponseSuccess = (checkUsersSavedEpisodesResponse200) & {
  headers: Headers;
};
export type checkUsersSavedEpisodesResponseError = (checkUsersSavedEpisodesResponse401 | checkUsersSavedEpisodesResponse403 | checkUsersSavedEpisodesResponse429) & {
  headers: Headers;
};

export type checkUsersSavedEpisodesResponse = (checkUsersSavedEpisodesResponseSuccess | checkUsersSavedEpisodesResponseError)

export const getCheckUsersSavedEpisodesUrl = (params: CheckUsersSavedEpisodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/episodes/contains?${stringifiedParams}` : `https://api.spotify.com/v1/me/episodes/contains`
}

export const checkUsersSavedEpisodes = async (params: CheckUsersSavedEpisodesParams, options?: RequestInit): Promise<checkUsersSavedEpisodesResponse> => {
  
  const res = await fetch(getCheckUsersSavedEpisodesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkUsersSavedEpisodesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkUsersSavedEpisodesResponse
}




export const getCheckUsersSavedEpisodesKey = (params: CheckUsersSavedEpisodesParams,) => [`https://api.spotify.com/v1/me/episodes/contains`, ...(params ? [params]: [])] as const;

export type CheckUsersSavedEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof checkUsersSavedEpisodes>>>

/**
 * @summary Check User's Saved Episodes

 */
export const useCheckUsersSavedEpisodes = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckUsersSavedEpisodesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkUsersSavedEpisodes>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckUsersSavedEpisodesKey(params) : null);
  const swrFn = () => checkUsersSavedEpisodes(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
