/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ArrayOfBooleansResponse,
  CheckCurrentUserFollowsParams,
  CheckIfUserFollowsPlaylistParams,
  CursorPagedArtistsResponse,
  FollowArtistsUsersBody,
  FollowArtistsUsersParams,
  FollowPlaylistBody,
  ForbiddenResponse,
  GetFollowedParams,
  GetUsersTopArtistsParams,
  GetUsersTopTracksParams,
  OnePrivateUserResponse,
  OnePublicUserResponse,
  PagingArtistObjectResponse,
  PagingTrackObjectResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
  UnfollowArtistsUsersBody,
  UnfollowArtistsUsersParams
} from '../../model';



  
  
  
/**
 * Get detailed profile information about the current user (including the
current user's username).

 * @summary Get Current User's Profile

 */
export type getCurrentUsersProfileResponse200 = {
  data: OnePrivateUserResponse
  status: 200
}

export type getCurrentUsersProfileResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCurrentUsersProfileResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getCurrentUsersProfileResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getCurrentUsersProfileResponseSuccess = (getCurrentUsersProfileResponse200) & {
  headers: Headers;
};
export type getCurrentUsersProfileResponseError = (getCurrentUsersProfileResponse401 | getCurrentUsersProfileResponse403 | getCurrentUsersProfileResponse429) & {
  headers: Headers;
};

export type getCurrentUsersProfileResponse = (getCurrentUsersProfileResponseSuccess | getCurrentUsersProfileResponseError)

export const getGetCurrentUsersProfileUrl = () => {


  

  return `https://api.spotify.com/v1/me`
}

export const getCurrentUsersProfile = async ( options?: RequestInit): Promise<getCurrentUsersProfileResponse> => {
  
  const res = await fetch(getGetCurrentUsersProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCurrentUsersProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCurrentUsersProfileResponse
}




export const getGetCurrentUsersProfileKey = () => [`https://api.spotify.com/v1/me`] as const;

export type GetCurrentUsersProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUsersProfile>>>

/**
 * @summary Get Current User's Profile

 */
export const useGetCurrentUsersProfile = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCurrentUsersProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCurrentUsersProfileKey() : null);
  const swrFn = () => getCurrentUsersProfile(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get public profile information about a Spotify user.

 * @summary Get User's Profile

 */
export type getUsersProfileResponse200 = {
  data: OnePublicUserResponse
  status: 200
}

export type getUsersProfileResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersProfileResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersProfileResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersProfileResponseSuccess = (getUsersProfileResponse200) & {
  headers: Headers;
};
export type getUsersProfileResponseError = (getUsersProfileResponse401 | getUsersProfileResponse403 | getUsersProfileResponse429) & {
  headers: Headers;
};

export type getUsersProfileResponse = (getUsersProfileResponseSuccess | getUsersProfileResponseError)

export const getGetUsersProfileUrl = (userId: string,) => {


  

  return `https://api.spotify.com/v1/users/${userId}`
}

export const getUsersProfile = async (userId: string, options?: RequestInit): Promise<getUsersProfileResponse> => {
  
  const res = await fetch(getGetUsersProfileUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersProfileResponse
}




export const getGetUsersProfileKey = (userId: string,) => [`https://api.spotify.com/v1/users/${userId}`] as const;

export type GetUsersProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersProfile>>>

/**
 * @summary Get User's Profile

 */
export const useGetUsersProfile = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  userId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(userId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersProfileKey(userId) : null);
  const swrFn = () => getUsersProfile(userId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Add the current user as a follower of a playlist.

 * @summary Follow Playlist

 */
export type followPlaylistResponse200 = {
  data: void
  status: 200
}

export type followPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type followPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type followPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type followPlaylistResponseSuccess = (followPlaylistResponse200) & {
  headers: Headers;
};
export type followPlaylistResponseError = (followPlaylistResponse401 | followPlaylistResponse403 | followPlaylistResponse429) & {
  headers: Headers;
};

export type followPlaylistResponse = (followPlaylistResponseSuccess | followPlaylistResponseError)

export const getFollowPlaylistUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}/followers`
}

export const followPlaylist = async (playlistId: string,
    followPlaylistBody: FollowPlaylistBody, options?: RequestInit): Promise<followPlaylistResponse> => {
  
  const res = await fetch(getFollowPlaylistUrl(playlistId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      followPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: followPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as followPlaylistResponse
}




export const getFollowPlaylistMutationFetcher = (playlistId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: FollowPlaylistBody }) => {
    return followPlaylist(playlistId, arg, options);
  }
}
export const getFollowPlaylistMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers`] as const;

export type FollowPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof followPlaylist>>>

/**
 * @summary Follow Playlist

 */
export const useFollowPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof followPlaylist>>, TError, Key, FollowPlaylistBody, Awaited<ReturnType<typeof followPlaylist>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFollowPlaylistMutationKey(playlistId);
  const swrFn = getFollowPlaylistMutationFetcher(playlistId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove the current user as a follower of a playlist.

 * @summary Unfollow Playlist

 */
export type unfollowPlaylistResponse200 = {
  data: void
  status: 200
}

export type unfollowPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type unfollowPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type unfollowPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type unfollowPlaylistResponseSuccess = (unfollowPlaylistResponse200) & {
  headers: Headers;
};
export type unfollowPlaylistResponseError = (unfollowPlaylistResponse401 | unfollowPlaylistResponse403 | unfollowPlaylistResponse429) & {
  headers: Headers;
};

export type unfollowPlaylistResponse = (unfollowPlaylistResponseSuccess | unfollowPlaylistResponseError)

export const getUnfollowPlaylistUrl = (playlistId: string,) => {


  

  return `https://api.spotify.com/v1/playlists/${playlistId}/followers`
}

export const unfollowPlaylist = async (playlistId: string, options?: RequestInit): Promise<unfollowPlaylistResponse> => {
  
  const res = await fetch(getUnfollowPlaylistUrl(playlistId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unfollowPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unfollowPlaylistResponse
}




export const getUnfollowPlaylistMutationFetcher = (playlistId: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return unfollowPlaylist(playlistId, options);
  }
}
export const getUnfollowPlaylistMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers`] as const;

export type UnfollowPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowPlaylist>>>

/**
 * @summary Unfollow Playlist

 */
export const useUnfollowPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof unfollowPlaylist>>, TError, Key, Arguments, Awaited<ReturnType<typeof unfollowPlaylist>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUnfollowPlaylistMutationKey(playlistId);
  const swrFn = getUnfollowPlaylistMutationFetcher(playlistId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's followed artists.

 * @summary Get Followed Artists

 */
export type getFollowedResponse200 = {
  data: CursorPagedArtistsResponse
  status: 200
}

export type getFollowedResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getFollowedResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getFollowedResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getFollowedResponseSuccess = (getFollowedResponse200) & {
  headers: Headers;
};
export type getFollowedResponseError = (getFollowedResponse401 | getFollowedResponse403 | getFollowedResponse429) & {
  headers: Headers;
};

export type getFollowedResponse = (getFollowedResponseSuccess | getFollowedResponseError)

export const getGetFollowedUrl = (params: GetFollowedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/following?${stringifiedParams}` : `https://api.spotify.com/v1/me/following`
}

export const getFollowed = async (params: GetFollowedParams, options?: RequestInit): Promise<getFollowedResponse> => {
  
  const res = await fetch(getGetFollowedUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getFollowedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getFollowedResponse
}




export const getGetFollowedKey = (params: GetFollowedParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type GetFollowedQueryResult = NonNullable<Awaited<ReturnType<typeof getFollowed>>>

/**
 * @summary Get Followed Artists

 */
export const useGetFollowed = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetFollowedParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFollowed>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFollowedKey(params) : null);
  const swrFn = () => getFollowed(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Add the current user as a follower of one or more artists or other Spotify users.

 * @summary Follow Artists or Users

 */
export type followArtistsUsersResponse204 = {
  data: void
  status: 204
}

export type followArtistsUsersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type followArtistsUsersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type followArtistsUsersResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type followArtistsUsersResponseSuccess = (followArtistsUsersResponse204) & {
  headers: Headers;
};
export type followArtistsUsersResponseError = (followArtistsUsersResponse401 | followArtistsUsersResponse403 | followArtistsUsersResponse429) & {
  headers: Headers;
};

export type followArtistsUsersResponse = (followArtistsUsersResponseSuccess | followArtistsUsersResponseError)

export const getFollowArtistsUsersUrl = (params: FollowArtistsUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/following?${stringifiedParams}` : `https://api.spotify.com/v1/me/following`
}

export const followArtistsUsers = async (followArtistsUsersBody: FollowArtistsUsersBody,
    params: FollowArtistsUsersParams, options?: RequestInit): Promise<followArtistsUsersResponse> => {
  
  const res = await fetch(getFollowArtistsUsersUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      followArtistsUsersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: followArtistsUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as followArtistsUsersResponse
}




export const getFollowArtistsUsersMutationFetcher = (params: FollowArtistsUsersParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: FollowArtistsUsersBody }) => {
    return followArtistsUsers(arg, params, options);
  }
}
export const getFollowArtistsUsersMutationKey = (params: FollowArtistsUsersParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type FollowArtistsUsersMutationResult = NonNullable<Awaited<ReturnType<typeof followArtistsUsers>>>

/**
 * @summary Follow Artists or Users

 */
export const useFollowArtistsUsers = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: FollowArtistsUsersParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof followArtistsUsers>>, TError, Key, FollowArtistsUsersBody, Awaited<ReturnType<typeof followArtistsUsers>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFollowArtistsUsersMutationKey(params);
  const swrFn = getFollowArtistsUsersMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove the current user as a follower of one or more artists or other Spotify users.

 * @summary Unfollow Artists or Users

 */
export type unfollowArtistsUsersResponse200 = {
  data: void
  status: 200
}

export type unfollowArtistsUsersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type unfollowArtistsUsersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type unfollowArtistsUsersResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type unfollowArtistsUsersResponseSuccess = (unfollowArtistsUsersResponse200) & {
  headers: Headers;
};
export type unfollowArtistsUsersResponseError = (unfollowArtistsUsersResponse401 | unfollowArtistsUsersResponse403 | unfollowArtistsUsersResponse429) & {
  headers: Headers;
};

export type unfollowArtistsUsersResponse = (unfollowArtistsUsersResponseSuccess | unfollowArtistsUsersResponseError)

export const getUnfollowArtistsUsersUrl = (params: UnfollowArtistsUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/following?${stringifiedParams}` : `https://api.spotify.com/v1/me/following`
}

export const unfollowArtistsUsers = async (unfollowArtistsUsersBody: UnfollowArtistsUsersBody,
    params: UnfollowArtistsUsersParams, options?: RequestInit): Promise<unfollowArtistsUsersResponse> => {
  
  const res = await fetch(getUnfollowArtistsUsersUrl(params),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      unfollowArtistsUsersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unfollowArtistsUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unfollowArtistsUsersResponse
}




export const getUnfollowArtistsUsersMutationFetcher = (params: UnfollowArtistsUsersParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UnfollowArtistsUsersBody }) => {
    return unfollowArtistsUsers(arg, params, options);
  }
}
export const getUnfollowArtistsUsersMutationKey = (params: UnfollowArtistsUsersParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type UnfollowArtistsUsersMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowArtistsUsers>>>

/**
 * @summary Unfollow Artists or Users

 */
export const useUnfollowArtistsUsers = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: UnfollowArtistsUsersParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof unfollowArtistsUsers>>, TError, Key, UnfollowArtistsUsersBody, Awaited<ReturnType<typeof unfollowArtistsUsers>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUnfollowArtistsUsersMutationKey(params);
  const swrFn = getUnfollowArtistsUsersMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check to see if the current user is following one or more artists or other Spotify users.

 * @summary Check If User Follows Artists or Users

 */
export type checkCurrentUserFollowsResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkCurrentUserFollowsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkCurrentUserFollowsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkCurrentUserFollowsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkCurrentUserFollowsResponseSuccess = (checkCurrentUserFollowsResponse200) & {
  headers: Headers;
};
export type checkCurrentUserFollowsResponseError = (checkCurrentUserFollowsResponse401 | checkCurrentUserFollowsResponse403 | checkCurrentUserFollowsResponse429) & {
  headers: Headers;
};

export type checkCurrentUserFollowsResponse = (checkCurrentUserFollowsResponseSuccess | checkCurrentUserFollowsResponseError)

export const getCheckCurrentUserFollowsUrl = (params: CheckCurrentUserFollowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/following/contains?${stringifiedParams}` : `https://api.spotify.com/v1/me/following/contains`
}

export const checkCurrentUserFollows = async (params: CheckCurrentUserFollowsParams, options?: RequestInit): Promise<checkCurrentUserFollowsResponse> => {
  
  const res = await fetch(getCheckCurrentUserFollowsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkCurrentUserFollowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkCurrentUserFollowsResponse
}




export const getCheckCurrentUserFollowsKey = (params: CheckCurrentUserFollowsParams,) => [`https://api.spotify.com/v1/me/following/contains`, ...(params ? [params]: [])] as const;

export type CheckCurrentUserFollowsQueryResult = NonNullable<Awaited<ReturnType<typeof checkCurrentUserFollows>>>

/**
 * @summary Check If User Follows Artists or Users

 */
export const useCheckCurrentUserFollows = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckCurrentUserFollowsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkCurrentUserFollows>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckCurrentUserFollowsKey(params) : null);
  const swrFn = () => checkCurrentUserFollows(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check to see if one or more Spotify users are following a specified playlist.

 * @summary Check if Users Follow Playlist

 */
export type checkIfUserFollowsPlaylistResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkIfUserFollowsPlaylistResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkIfUserFollowsPlaylistResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkIfUserFollowsPlaylistResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkIfUserFollowsPlaylistResponseSuccess = (checkIfUserFollowsPlaylistResponse200) & {
  headers: Headers;
};
export type checkIfUserFollowsPlaylistResponseError = (checkIfUserFollowsPlaylistResponse401 | checkIfUserFollowsPlaylistResponse403 | checkIfUserFollowsPlaylistResponse429) & {
  headers: Headers;
};

export type checkIfUserFollowsPlaylistResponse = (checkIfUserFollowsPlaylistResponseSuccess | checkIfUserFollowsPlaylistResponseError)

export const getCheckIfUserFollowsPlaylistUrl = (playlistId: string,
    params: CheckIfUserFollowsPlaylistParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/playlists/${playlistId}/followers/contains?${stringifiedParams}` : `https://api.spotify.com/v1/playlists/${playlistId}/followers/contains`
}

export const checkIfUserFollowsPlaylist = async (playlistId: string,
    params: CheckIfUserFollowsPlaylistParams, options?: RequestInit): Promise<checkIfUserFollowsPlaylistResponse> => {
  
  const res = await fetch(getCheckIfUserFollowsPlaylistUrl(playlistId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkIfUserFollowsPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkIfUserFollowsPlaylistResponse
}




export const getCheckIfUserFollowsPlaylistKey = (playlistId: string,
    params: CheckIfUserFollowsPlaylistParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers/contains`, ...(params ? [params]: [])] as const;

export type CheckIfUserFollowsPlaylistQueryResult = NonNullable<Awaited<ReturnType<typeof checkIfUserFollowsPlaylist>>>

/**
 * @summary Check if Users Follow Playlist

 */
export const useCheckIfUserFollowsPlaylist = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params: CheckIfUserFollowsPlaylistParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkIfUserFollowsPlaylist>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(playlistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckIfUserFollowsPlaylistKey(playlistId,params) : null);
  const swrFn = () => checkIfUserFollowsPlaylist(playlistId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's top artists based on calculated affinity.

 * @summary Get User's Top Artists

 */
export type getUsersTopArtistsResponse200 = {
  data: PagingArtistObjectResponse
  status: 200
}

export type getUsersTopArtistsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersTopArtistsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersTopArtistsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersTopArtistsResponseSuccess = (getUsersTopArtistsResponse200) & {
  headers: Headers;
};
export type getUsersTopArtistsResponseError = (getUsersTopArtistsResponse401 | getUsersTopArtistsResponse403 | getUsersTopArtistsResponse429) & {
  headers: Headers;
};

export type getUsersTopArtistsResponse = (getUsersTopArtistsResponseSuccess | getUsersTopArtistsResponseError)

export const getGetUsersTopArtistsUrl = (params?: GetUsersTopArtistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/top/artists?${stringifiedParams}` : `https://api.spotify.com/v1/me/top/artists`
}

export const getUsersTopArtists = async (params?: GetUsersTopArtistsParams, options?: RequestInit): Promise<getUsersTopArtistsResponse> => {
  
  const res = await fetch(getGetUsersTopArtistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersTopArtistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersTopArtistsResponse
}




export const getGetUsersTopArtistsKey = (params?: GetUsersTopArtistsParams,) => [`https://api.spotify.com/v1/me/top/artists`, ...(params ? [params]: [])] as const;

export type GetUsersTopArtistsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersTopArtists>>>

/**
 * @summary Get User's Top Artists

 */
export const useGetUsersTopArtists = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersTopArtistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersTopArtists>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersTopArtistsKey(params) : null);
  const swrFn = () => getUsersTopArtists(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's top tracks based on calculated affinity.

 * @summary Get User's Top Tracks

 */
export type getUsersTopTracksResponse200 = {
  data: PagingTrackObjectResponse
  status: 200
}

export type getUsersTopTracksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersTopTracksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersTopTracksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersTopTracksResponseSuccess = (getUsersTopTracksResponse200) & {
  headers: Headers;
};
export type getUsersTopTracksResponseError = (getUsersTopTracksResponse401 | getUsersTopTracksResponse403 | getUsersTopTracksResponse429) & {
  headers: Headers;
};

export type getUsersTopTracksResponse = (getUsersTopTracksResponseSuccess | getUsersTopTracksResponseError)

export const getGetUsersTopTracksUrl = (params?: GetUsersTopTracksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/top/tracks?${stringifiedParams}` : `https://api.spotify.com/v1/me/top/tracks`
}

export const getUsersTopTracks = async (params?: GetUsersTopTracksParams, options?: RequestInit): Promise<getUsersTopTracksResponse> => {
  
  const res = await fetch(getGetUsersTopTracksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersTopTracksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersTopTracksResponse
}




export const getGetUsersTopTracksKey = (params?: GetUsersTopTracksParams,) => [`https://api.spotify.com/v1/me/top/tracks`, ...(params ? [params]: [])] as const;

export type GetUsersTopTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersTopTracks>>>

/**
 * @summary Get User's Top Tracks

 */
export const useGetUsersTopTracks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersTopTracksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersTopTracks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersTopTracksKey(params) : null);
  const swrFn = () => getUsersTopTracks(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
