/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  GetAChapterParams,
  GetSeveralChaptersParams,
  ManyChaptersResponse,
  OneChapterResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single chapter.<br />
**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Get a Chapter

 */
export type getAChapterResponse200 = {
  data: OneChapterResponse
  status: 200
}

export type getAChapterResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAChapterResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAChapterResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAChapterResponseSuccess = (getAChapterResponse200) & {
  headers: Headers;
};
export type getAChapterResponseError = (getAChapterResponse401 | getAChapterResponse403 | getAChapterResponse429) & {
  headers: Headers;
};

export type getAChapterResponse = (getAChapterResponseSuccess | getAChapterResponseError)

export const getGetAChapterUrl = (id: string,
    params?: GetAChapterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/chapters/${id}?${stringifiedParams}` : `https://api.spotify.com/v1/chapters/${id}`
}

export const getAChapter = async (id: string,
    params?: GetAChapterParams, options?: RequestInit): Promise<getAChapterResponse> => {
  
  const res = await fetch(getGetAChapterUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAChapterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAChapterResponse
}




export const getGetAChapterKey = (id: string,
    params?: GetAChapterParams,) => [`https://api.spotify.com/v1/chapters/${id}`, ...(params ? [params]: [])] as const;

export type GetAChapterQueryResult = NonNullable<Awaited<ReturnType<typeof getAChapter>>>

/**
 * @summary Get a Chapter

 */
export const useGetAChapter = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAChapterParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAChapter>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAChapterKey(id,params) : null);
  const swrFn = () => getAChapter(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for several chapters identified by their Spotify IDs.<br />
**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Get Several Chapters

 */
export type getSeveralChaptersResponse200 = {
  data: ManyChaptersResponse
  status: 200
}

export type getSeveralChaptersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSeveralChaptersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSeveralChaptersResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getSeveralChaptersResponseSuccess = (getSeveralChaptersResponse200) & {
  headers: Headers;
};
export type getSeveralChaptersResponseError = (getSeveralChaptersResponse401 | getSeveralChaptersResponse403 | getSeveralChaptersResponse429) & {
  headers: Headers;
};

export type getSeveralChaptersResponse = (getSeveralChaptersResponseSuccess | getSeveralChaptersResponseError)

export const getGetSeveralChaptersUrl = (params: GetSeveralChaptersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/chapters?${stringifiedParams}` : `https://api.spotify.com/v1/chapters`
}

export const getSeveralChapters = async (params: GetSeveralChaptersParams, options?: RequestInit): Promise<getSeveralChaptersResponse> => {
  
  const res = await fetch(getGetSeveralChaptersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSeveralChaptersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSeveralChaptersResponse
}




export const getGetSeveralChaptersKey = (params: GetSeveralChaptersParams,) => [`https://api.spotify.com/v1/chapters`, ...(params ? [params]: [])] as const;

export type GetSeveralChaptersQueryResult = NonNullable<Awaited<ReturnType<typeof getSeveralChapters>>>

/**
 * @summary Get Several Chapters

 */
export const useGetSeveralChapters = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetSeveralChaptersParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSeveralChapters>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSeveralChaptersKey(params) : null);
  const swrFn = () => getSeveralChapters(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
