/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  MarketsResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get the list of markets where Spotify is available.

 * @summary Get Available Markets

 */
export type getAvailableMarketsResponse200 = {
  data: MarketsResponse
  status: 200
}

export type getAvailableMarketsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAvailableMarketsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAvailableMarketsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAvailableMarketsResponseSuccess = (getAvailableMarketsResponse200) & {
  headers: Headers;
};
export type getAvailableMarketsResponseError = (getAvailableMarketsResponse401 | getAvailableMarketsResponse403 | getAvailableMarketsResponse429) & {
  headers: Headers;
};

export type getAvailableMarketsResponse = (getAvailableMarketsResponseSuccess | getAvailableMarketsResponseError)

export const getGetAvailableMarketsUrl = () => {


  

  return `https://api.spotify.com/v1/markets`
}

export const getAvailableMarkets = async ( options?: RequestInit): Promise<getAvailableMarketsResponse> => {
  
  const res = await fetch(getGetAvailableMarketsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAvailableMarketsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAvailableMarketsResponse
}




export const getGetAvailableMarketsKey = () => [`https://api.spotify.com/v1/markets`] as const;

export type GetAvailableMarketsQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailableMarkets>>>

/**
 * @summary Get Available Markets

 */
export const useGetAvailableMarkets = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAvailableMarkets>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAvailableMarketsKey() : null);
  const swrFn = () => getAvailableMarkets(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
