/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ArrayOfBooleansResponse,
  CheckUsersSavedAlbumsParams,
  ForbiddenResponse,
  GetAnAlbumParams,
  GetAnAlbumsTracksParams,
  GetMultipleAlbumsParams,
  GetNewReleasesParams,
  GetUsersSavedAlbumsParams,
  ManyAlbumsResponse,
  OneAlbumResponse,
  PagedAlbumsResponse,
  PagingSavedAlbumObjectResponse,
  PagingSimplifiedTrackObjectResponse,
  RemoveAlbumsUserBody,
  RemoveAlbumsUserParams,
  SaveAlbumsUserBody,
  SaveAlbumsUserParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information for a single album.

 * @summary Get Album

 */
export type getAnAlbumResponse200 = {
  data: OneAlbumResponse
  status: 200
}

export type getAnAlbumResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnAlbumResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnAlbumResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnAlbumResponseSuccess = (getAnAlbumResponse200) & {
  headers: Headers;
};
export type getAnAlbumResponseError = (getAnAlbumResponse401 | getAnAlbumResponse403 | getAnAlbumResponse429) & {
  headers: Headers;
};

export type getAnAlbumResponse = (getAnAlbumResponseSuccess | getAnAlbumResponseError)

export const getGetAnAlbumUrl = (id: string,
    params?: GetAnAlbumParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/albums/${id}?${stringifiedParams}` : `https://api.spotify.com/v1/albums/${id}`
}

export const getAnAlbum = async (id: string,
    params?: GetAnAlbumParams, options?: RequestInit): Promise<getAnAlbumResponse> => {
  
  const res = await fetch(getGetAnAlbumUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnAlbumResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnAlbumResponse
}




export const getGetAnAlbumKey = (id: string,
    params?: GetAnAlbumParams,) => [`https://api.spotify.com/v1/albums/${id}`, ...(params ? [params]: [])] as const;

export type GetAnAlbumQueryResult = NonNullable<Awaited<ReturnType<typeof getAnAlbum>>>

/**
 * @summary Get Album

 */
export const useGetAnAlbum = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnAlbumParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnAlbum>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnAlbumKey(id,params) : null);
  const swrFn = () => getAnAlbum(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information for multiple albums identified by their Spotify IDs.

 * @summary Get Several Albums

 */
export type getMultipleAlbumsResponse200 = {
  data: ManyAlbumsResponse
  status: 200
}

export type getMultipleAlbumsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMultipleAlbumsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMultipleAlbumsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getMultipleAlbumsResponseSuccess = (getMultipleAlbumsResponse200) & {
  headers: Headers;
};
export type getMultipleAlbumsResponseError = (getMultipleAlbumsResponse401 | getMultipleAlbumsResponse403 | getMultipleAlbumsResponse429) & {
  headers: Headers;
};

export type getMultipleAlbumsResponse = (getMultipleAlbumsResponseSuccess | getMultipleAlbumsResponseError)

export const getGetMultipleAlbumsUrl = (params: GetMultipleAlbumsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/albums?${stringifiedParams}` : `https://api.spotify.com/v1/albums`
}

export const getMultipleAlbums = async (params: GetMultipleAlbumsParams, options?: RequestInit): Promise<getMultipleAlbumsResponse> => {
  
  const res = await fetch(getGetMultipleAlbumsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMultipleAlbumsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMultipleAlbumsResponse
}




export const getGetMultipleAlbumsKey = (params: GetMultipleAlbumsParams,) => [`https://api.spotify.com/v1/albums`, ...(params ? [params]: [])] as const;

export type GetMultipleAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleAlbums>>>

/**
 * @summary Get Several Albums

 */
export const useGetMultipleAlbums = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetMultipleAlbumsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMultipleAlbums>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMultipleAlbumsKey(params) : null);
  const swrFn = () => getMultipleAlbums(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get Spotify catalog information about an album’s tracks.
Optional parameters can be used to limit the number of tracks returned.

 * @summary Get Album Tracks

 */
export type getAnAlbumsTracksResponse200 = {
  data: PagingSimplifiedTrackObjectResponse
  status: 200
}

export type getAnAlbumsTracksResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAnAlbumsTracksResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getAnAlbumsTracksResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getAnAlbumsTracksResponseSuccess = (getAnAlbumsTracksResponse200) & {
  headers: Headers;
};
export type getAnAlbumsTracksResponseError = (getAnAlbumsTracksResponse401 | getAnAlbumsTracksResponse403 | getAnAlbumsTracksResponse429) & {
  headers: Headers;
};

export type getAnAlbumsTracksResponse = (getAnAlbumsTracksResponseSuccess | getAnAlbumsTracksResponseError)

export const getGetAnAlbumsTracksUrl = (id: string,
    params?: GetAnAlbumsTracksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/albums/${id}/tracks?${stringifiedParams}` : `https://api.spotify.com/v1/albums/${id}/tracks`
}

export const getAnAlbumsTracks = async (id: string,
    params?: GetAnAlbumsTracksParams, options?: RequestInit): Promise<getAnAlbumsTracksResponse> => {
  
  const res = await fetch(getGetAnAlbumsTracksUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnAlbumsTracksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnAlbumsTracksResponse
}




export const getGetAnAlbumsTracksKey = (id: string,
    params?: GetAnAlbumsTracksParams,) => [`https://api.spotify.com/v1/albums/${id}/tracks`, ...(params ? [params]: [])] as const;

export type GetAnAlbumsTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getAnAlbumsTracks>>>

/**
 * @summary Get Album Tracks

 */
export const useGetAnAlbumsTracks = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  id: string,
    params?: GetAnAlbumsTracksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAnAlbumsTracks>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAnAlbumsTracksKey(id,params) : null);
  const swrFn = () => getAnAlbumsTracks(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of the albums saved in the current Spotify user's 'Your Music' library.

 * @summary Get User's Saved Albums

 */
export type getUsersSavedAlbumsResponse200 = {
  data: PagingSavedAlbumObjectResponse
  status: 200
}

export type getUsersSavedAlbumsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUsersSavedAlbumsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUsersSavedAlbumsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getUsersSavedAlbumsResponseSuccess = (getUsersSavedAlbumsResponse200) & {
  headers: Headers;
};
export type getUsersSavedAlbumsResponseError = (getUsersSavedAlbumsResponse401 | getUsersSavedAlbumsResponse403 | getUsersSavedAlbumsResponse429) & {
  headers: Headers;
};

export type getUsersSavedAlbumsResponse = (getUsersSavedAlbumsResponseSuccess | getUsersSavedAlbumsResponseError)

export const getGetUsersSavedAlbumsUrl = (params?: GetUsersSavedAlbumsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/albums?${stringifiedParams}` : `https://api.spotify.com/v1/me/albums`
}

export const getUsersSavedAlbums = async (params?: GetUsersSavedAlbumsParams, options?: RequestInit): Promise<getUsersSavedAlbumsResponse> => {
  
  const res = await fetch(getGetUsersSavedAlbumsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersSavedAlbumsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersSavedAlbumsResponse
}




export const getGetUsersSavedAlbumsKey = (params?: GetUsersSavedAlbumsParams,) => [`https://api.spotify.com/v1/me/albums`, ...(params ? [params]: [])] as const;

export type GetUsersSavedAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersSavedAlbums>>>

/**
 * @summary Get User's Saved Albums

 */
export const useGetUsersSavedAlbums = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersSavedAlbumsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersSavedAlbums>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersSavedAlbumsKey(params) : null);
  const swrFn = () => getUsersSavedAlbums(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Save one or more albums to the current user's 'Your Music' library.

 * @summary Save Albums for Current User

 */
export type saveAlbumsUserResponse200 = {
  data: void
  status: 200
}

export type saveAlbumsUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type saveAlbumsUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type saveAlbumsUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type saveAlbumsUserResponseSuccess = (saveAlbumsUserResponse200) & {
  headers: Headers;
};
export type saveAlbumsUserResponseError = (saveAlbumsUserResponse401 | saveAlbumsUserResponse403 | saveAlbumsUserResponse429) & {
  headers: Headers;
};

export type saveAlbumsUserResponse = (saveAlbumsUserResponseSuccess | saveAlbumsUserResponseError)

export const getSaveAlbumsUserUrl = (params: SaveAlbumsUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/albums?${stringifiedParams}` : `https://api.spotify.com/v1/me/albums`
}

export const saveAlbumsUser = async (saveAlbumsUserBody: SaveAlbumsUserBody,
    params: SaveAlbumsUserParams, options?: RequestInit): Promise<saveAlbumsUserResponse> => {
  
  const res = await fetch(getSaveAlbumsUserUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveAlbumsUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: saveAlbumsUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveAlbumsUserResponse
}




export const getSaveAlbumsUserMutationFetcher = (params: SaveAlbumsUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: SaveAlbumsUserBody }) => {
    return saveAlbumsUser(arg, params, options);
  }
}
export const getSaveAlbumsUserMutationKey = (params: SaveAlbumsUserParams,) => [`https://api.spotify.com/v1/me/albums`, ...(params ? [params]: [])] as const;

export type SaveAlbumsUserMutationResult = NonNullable<Awaited<ReturnType<typeof saveAlbumsUser>>>

/**
 * @summary Save Albums for Current User

 */
export const useSaveAlbumsUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: SaveAlbumsUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof saveAlbumsUser>>, TError, Key, SaveAlbumsUserBody, Awaited<ReturnType<typeof saveAlbumsUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSaveAlbumsUserMutationKey(params);
  const swrFn = getSaveAlbumsUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove one or more albums from the current user's 'Your Music' library.

 * @summary Remove Users' Saved Albums

 */
export type removeAlbumsUserResponse200 = {
  data: void
  status: 200
}

export type removeAlbumsUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeAlbumsUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeAlbumsUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type removeAlbumsUserResponseSuccess = (removeAlbumsUserResponse200) & {
  headers: Headers;
};
export type removeAlbumsUserResponseError = (removeAlbumsUserResponse401 | removeAlbumsUserResponse403 | removeAlbumsUserResponse429) & {
  headers: Headers;
};

export type removeAlbumsUserResponse = (removeAlbumsUserResponseSuccess | removeAlbumsUserResponseError)

export const getRemoveAlbumsUserUrl = (params: RemoveAlbumsUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/albums?${stringifiedParams}` : `https://api.spotify.com/v1/me/albums`
}

export const removeAlbumsUser = async (removeAlbumsUserBody: RemoveAlbumsUserBody,
    params: RemoveAlbumsUserParams, options?: RequestInit): Promise<removeAlbumsUserResponse> => {
  
  const res = await fetch(getRemoveAlbumsUserUrl(params),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeAlbumsUserBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeAlbumsUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeAlbumsUserResponse
}




export const getRemoveAlbumsUserMutationFetcher = (params: RemoveAlbumsUserParams, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RemoveAlbumsUserBody }) => {
    return removeAlbumsUser(arg, params, options);
  }
}
export const getRemoveAlbumsUserMutationKey = (params: RemoveAlbumsUserParams,) => [`https://api.spotify.com/v1/me/albums`, ...(params ? [params]: [])] as const;

export type RemoveAlbumsUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeAlbumsUser>>>

/**
 * @summary Remove Users' Saved Albums

 */
export const useRemoveAlbumsUser = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: RemoveAlbumsUserParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeAlbumsUser>>, TError, Key, RemoveAlbumsUserBody, Awaited<ReturnType<typeof removeAlbumsUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveAlbumsUserMutationKey(params);
  const swrFn = getRemoveAlbumsUserMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.

 * @summary Check User's Saved Albums

 */
export type checkUsersSavedAlbumsResponse200 = {
  data: ArrayOfBooleansResponse
  status: 200
}

export type checkUsersSavedAlbumsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkUsersSavedAlbumsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkUsersSavedAlbumsResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type checkUsersSavedAlbumsResponseSuccess = (checkUsersSavedAlbumsResponse200) & {
  headers: Headers;
};
export type checkUsersSavedAlbumsResponseError = (checkUsersSavedAlbumsResponse401 | checkUsersSavedAlbumsResponse403 | checkUsersSavedAlbumsResponse429) & {
  headers: Headers;
};

export type checkUsersSavedAlbumsResponse = (checkUsersSavedAlbumsResponseSuccess | checkUsersSavedAlbumsResponseError)

export const getCheckUsersSavedAlbumsUrl = (params: CheckUsersSavedAlbumsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/me/albums/contains?${stringifiedParams}` : `https://api.spotify.com/v1/me/albums/contains`
}

export const checkUsersSavedAlbums = async (params: CheckUsersSavedAlbumsParams, options?: RequestInit): Promise<checkUsersSavedAlbumsResponse> => {
  
  const res = await fetch(getCheckUsersSavedAlbumsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkUsersSavedAlbumsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkUsersSavedAlbumsResponse
}




export const getCheckUsersSavedAlbumsKey = (params: CheckUsersSavedAlbumsParams,) => [`https://api.spotify.com/v1/me/albums/contains`, ...(params ? [params]: [])] as const;

export type CheckUsersSavedAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof checkUsersSavedAlbums>>>

/**
 * @summary Check User's Saved Albums

 */
export const useCheckUsersSavedAlbums = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckUsersSavedAlbumsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkUsersSavedAlbums>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckUsersSavedAlbumsKey(params) : null);
  const swrFn = () => checkUsersSavedAlbums(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).

 * @summary Get New Releases

 */
export type getNewReleasesResponse200 = {
  data: PagedAlbumsResponse
  status: 200
}

export type getNewReleasesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getNewReleasesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getNewReleasesResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type getNewReleasesResponseSuccess = (getNewReleasesResponse200) & {
  headers: Headers;
};
export type getNewReleasesResponseError = (getNewReleasesResponse401 | getNewReleasesResponse403 | getNewReleasesResponse429) & {
  headers: Headers;
};

export type getNewReleasesResponse = (getNewReleasesResponseSuccess | getNewReleasesResponseError)

export const getGetNewReleasesUrl = (params?: GetNewReleasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/browse/new-releases?${stringifiedParams}` : `https://api.spotify.com/v1/browse/new-releases`
}

export const getNewReleases = async (params?: GetNewReleasesParams, options?: RequestInit): Promise<getNewReleasesResponse> => {
  
  const res = await fetch(getGetNewReleasesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getNewReleasesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNewReleasesResponse
}




export const getGetNewReleasesKey = (params?: GetNewReleasesParams,) => [`https://api.spotify.com/v1/browse/new-releases`, ...(params ? [params]: [])] as const;

export type GetNewReleasesQueryResult = NonNullable<Awaited<ReturnType<typeof getNewReleases>>>

/**
 * @summary Get New Releases

 */
export const useGetNewReleases = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetNewReleasesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getNewReleases>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetNewReleasesKey(params) : null);
  const swrFn = () => getNewReleases(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
