/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ForbiddenResponse,
  SearchItemsResponse,
  SearchParams,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';



  
  
  
/**
 * Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks
that match a keyword string.<br />
**Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**

 * @summary Search for Item

 */
export type searchResponse200 = {
  data: SearchItemsResponse
  status: 200
}

export type searchResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type searchResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type searchResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}
    
export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
export type searchResponseError = (searchResponse401 | searchResponse403 | searchResponse429) & {
  headers: Headers;
};

export type searchResponse = (searchResponseSuccess | searchResponseError)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.spotify.com/v1/search?${stringifiedParams}` : `https://api.spotify.com/v1/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {
  
  const res = await fetch(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: searchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchResponse
}




export const getSearchKey = (params: SearchParams,) => [`https://api.spotify.com/v1/search`, ...(params ? [params]: [])] as const;

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>

/**
 * @summary Search for Item

 */
export const useSearch = <TError = Promise<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: SearchParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof search>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getSearchKey(params) : null);
  const swrFn = () => search(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
